/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * Amazing EKB backend contract.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * @summary Administrative content source list.
 */
export const AdminContentSourcesListQueryParams = zod.strictObject({
  platform: zod.enum(['telegram', 'dzen', 'instagram', 'tiktok', 'vk', 'pinterest']).optional(),
  status: zod.enum(['active', 'disabled']).optional(),
});

export const AdminContentSourcesList200Response = zod.strictObject({
  items: zod.array(
    zod.strictObject({
      channelId: zod.string().nullable(),
      createdAt: zod.iso.datetime({ offset: true }),
      displayName: zod.string(),
      externalId: zod.string().nullable(),
      handle: zod.string().nullable(),
      id: zod.string(),
      lastCursor: zod.string().nullable(),
      lastImportedAt: zod.iso.datetime({ offset: true }).nullable(),
      platform: zod.enum(['telegram', 'dzen', 'instagram', 'tiktok', 'vk', 'pinterest']),
      status: zod.enum(['active', 'disabled']),
      updatedAt: zod.iso.datetime({ offset: true }),
      url: zod.url(),
    }),
  ),
});

/**
 * @summary Created content source.
 */

export const AdminContentSourcesCreateBody = zod.strictObject({
  channelId: zod.string().min(1).nullish(),
  displayName: zod.string().min(1),
  externalId: zod.string().min(1).nullish(),
  handle: zod.string().min(1).nullish(),
  platform: zod.enum(['telegram', 'dzen', 'instagram', 'tiktok', 'vk', 'pinterest']),
  url: zod.url(),
});

export const AdminContentSourcesCreate201Response = zod.strictObject({
  channelId: zod.string().nullable(),
  createdAt: zod.iso.datetime({ offset: true }),
  displayName: zod.string(),
  externalId: zod.string().nullable(),
  handle: zod.string().nullable(),
  id: zod.string(),
  lastCursor: zod.string().nullable(),
  lastImportedAt: zod.iso.datetime({ offset: true }).nullable(),
  platform: zod.enum(['telegram', 'dzen', 'instagram', 'tiktok', 'vk', 'pinterest']),
  status: zod.enum(['active', 'disabled']),
  updatedAt: zod.iso.datetime({ offset: true }),
  url: zod.url(),
});

/**
 * @summary Updated content source.
 */
export const AdminContentSourcesUpdateParams = zod.strictObject({
  sourceId: zod.string(),
});

export const AdminContentSourcesUpdateBody = zod.strictObject({
  channelId: zod.string().min(1).nullish(),
  displayName: zod.string().min(1).optional(),
  externalId: zod.string().min(1).nullish(),
  handle: zod.string().min(1).nullish(),
  url: zod.url().optional(),
});

export const AdminContentSourcesUpdate200Response = zod.strictObject({
  channelId: zod.string().nullable(),
  createdAt: zod.iso.datetime({ offset: true }),
  displayName: zod.string(),
  externalId: zod.string().nullable(),
  handle: zod.string().nullable(),
  id: zod.string(),
  lastCursor: zod.string().nullable(),
  lastImportedAt: zod.iso.datetime({ offset: true }).nullable(),
  platform: zod.enum(['telegram', 'dzen', 'instagram', 'tiktok', 'vk', 'pinterest']),
  status: zod.enum(['active', 'disabled']),
  updatedAt: zod.iso.datetime({ offset: true }),
  url: zod.url(),
});

/**
 * @summary Queued Telegram import run.
 */
export const AdminTelegramImportsEnqueueParams = zod.strictObject({
  sourceId: zod.string(),
});

export const adminTelegramImportsEnqueueQueryLimitDefault = 50;
export const adminTelegramImportsEnqueueQueryLimitMax = 100;

export const AdminTelegramImportsEnqueueQueryParams = zod.strictObject({
  limit: zod
    .number()
    .min(1)
    .max(adminTelegramImportsEnqueueQueryLimitMax)
    .default(adminTelegramImportsEnqueueQueryLimitDefault),
});

export const adminTelegramImportsEnqueue201ResponseCreatedCountMin = 0;

export const adminTelegramImportsEnqueue201ResponseFoundCountMin = 0;

export const adminTelegramImportsEnqueue201ResponseSkippedDuplicateCountMin = 0;

export const adminTelegramImportsEnqueue201ResponseUpdatedCountMin = 0;

export const AdminTelegramImportsEnqueue201Response = zod.strictObject({
  createdAt: zod.iso.datetime({ offset: true }),
  createdCount: zod.number().min(adminTelegramImportsEnqueue201ResponseCreatedCountMin),
  errorMessage: zod.string().nullable(),
  finishedAt: zod.iso.datetime({ offset: true }).nullable(),
  foundCount: zod.number().min(adminTelegramImportsEnqueue201ResponseFoundCountMin),
  id: zod.string(),
  skippedDuplicateCount: zod
    .number()
    .min(adminTelegramImportsEnqueue201ResponseSkippedDuplicateCountMin),
  sourceId: zod.string(),
  startedAt: zod.iso.datetime({ offset: true }).nullable(),
  status: zod.enum(['queued', 'running', 'completed', 'failed']),
  updatedAt: zod.iso.datetime({ offset: true }),
  updatedCount: zod.number().min(adminTelegramImportsEnqueue201ResponseUpdatedCountMin),
});

/**
 * @summary Content source with updated status.
 */
export const AdminContentSourcesUpdateStatusParams = zod.strictObject({
  sourceId: zod.string(),
});

export const AdminContentSourcesUpdateStatusBody = zod.strictObject({
  status: zod.enum(['active', 'disabled']),
});

export const AdminContentSourcesUpdateStatus200Response = zod.strictObject({
  channelId: zod.string().nullable(),
  createdAt: zod.iso.datetime({ offset: true }),
  displayName: zod.string(),
  externalId: zod.string().nullable(),
  handle: zod.string().nullable(),
  id: zod.string(),
  lastCursor: zod.string().nullable(),
  lastImportedAt: zod.iso.datetime({ offset: true }).nullable(),
  platform: zod.enum(['telegram', 'dzen', 'instagram', 'tiktok', 'vk', 'pinterest']),
  status: zod.enum(['active', 'disabled']),
  updatedAt: zod.iso.datetime({ offset: true }),
  url: zod.url(),
});
