/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * Amazing EKB backend contract.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * @summary Public collection list.
 */

export const CollectionsList200Response = zod.strictObject({
  items: zod.array(
    zod.strictObject({
      coverImageUrl: zod.string().nullable(),
      description: zod.string().nullable(),
      id: zod.string(),
      placeCount: zod.number().min(1),
      slug: zod.string(),
      title: zod.string(),
    }),
  ),
});

/**
 * @summary Public collection detail.
 */
export const CollectionsGetParams = zod.strictObject({
  collectionSlug: zod.string(),
});

export const collectionsGetQueryPageSizeDefault = 20;
export const collectionsGetQueryPageSizeMax = 100;

export const collectionsGetQueryPageDefault = 1;
export const collectionsGetQueryPageMax = 1000;

export const CollectionsGetQueryParams = zod.strictObject({
  pageSize: zod
    .number()
    .min(1)
    .max(collectionsGetQueryPageSizeMax)
    .default(collectionsGetQueryPageSizeDefault),
  page: zod.number().min(1).max(collectionsGetQueryPageMax).default(collectionsGetQueryPageDefault),
});

export const collectionsGet200ResponseItemsItemCountersDzenMin = 0;

export const collectionsGet200ResponseItemsItemCountersInstagramMin = 0;

export const collectionsGet200ResponseItemsItemCountersTelegramMin = 0;

export const collectionsGet200ResponseTotalMin = 0;

export const CollectionsGet200Response = zod.strictObject({
  coverImageUrl: zod.string().nullable(),
  description: zod.string().nullable(),
  id: zod.string(),
  items: zod.array(
    zod.strictObject({
      category: zod.strictObject({
        coverImageUrl: zod.string().nullable(),
        id: zod.string(),
        slug: zod.string(),
        title: zod.string(),
      }),
      counters: zod.strictObject({
        dzen: zod.number().min(collectionsGet200ResponseItemsItemCountersDzenMin),
        instagram: zod.number().min(collectionsGet200ResponseItemsItemCountersInstagramMin),
        telegram: zod.number().min(collectionsGet200ResponseItemsItemCountersTelegramMin),
      }),
      coverImageUrl: zod.string().nullable(),
      id: zod.string(),
      slug: zod.string(),
      status: zod.enum(['active', 'hidden']),
      summary: zod.string(),
      tags: zod.array(zod.string()),
      title: zod.string(),
    }),
  ),
  page: zod.number().min(1),
  pageSize: zod.number().min(1),
  slug: zod.string(),
  title: zod.string(),
  total: zod.number().min(collectionsGet200ResponseTotalMin),
});

/**
 * @summary Public collection cover image.
 */
export const CollectionsGetPhotoParams = zod.strictObject({
  collectionSlug: zod.string(),
});
