/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * MVP backend API (OpenAPI-first)
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * Возвращает список избранных мест текущего аутентифицированного пользователя.
 * @summary List favorites
 */
export const ListFavorites200Response = zod
  .strictObject({
    items: zod
      .array(
        zod
          .strictObject({
            id: zod.string().describe('Идентификатор места.'),
            title: zod.string().describe('Название места.'),
            summary: zod.string().describe('Короткое описание для каталога.'),
            tags: zod.array(zod.string()).describe('Набор тегов для поиска и фильтрации.'),
            category: zod
              .enum(['pools', 'spa', 'cafe', 'hotels', 'workshops'])
              .describe('Категория места в каталоге.'),
            status: zod.enum(['active', 'hidden']).describe('Статус публикации места.'),
            popularityWeight: zod.number().describe('Вес популярности для сортировки.'),
            coverImageUrl: zod
              .string()
              .nullable()
              .describe(
                'Публичный cover-фото места. Если фото отсутствует или не должно отдаться публично, возвращается `null`.',
              ),
          })
          .describe('Краткая карточка места, используемая в списках.'),
      )
      .describe('Элементы текущей страницы.'),
    total: zod.number().describe('Общее количество доступных элементов.'),
    page: zod.number().describe('Текущая страница.'),
    pageSize: zod.number().describe('Размер страницы.'),
  })
  .describe('Пагинированный список мест.');

export const ListFavorites401Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

/**
 * Добавляет место в избранное текущего пользователя.
 * @summary Add favorite
 */
export const AddFavoriteParams = zod.strictObject({
  placeId: zod.string().describe('Идентификатор места.'),
});

export const AddFavorite401Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const AddFavorite404Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

/**
 * Удаляет место из избранного текущего пользователя.
 * @summary Remove favorite
 */
export const RemoveFavoriteParams = zod.strictObject({
  placeId: zod.string().describe('Идентификатор места.'),
});

export const RemoveFavorite401Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');
