/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * MVP backend API (OpenAPI-first)
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * Возвращает список избранных мест текущего аутентифицированного пользователя.
 * @summary List favorites
 */
export const ListFavorites200Response = zod
  .strictObject({
    items: zod
      .array(
        zod
          .strictObject({
            id: zod.string().describe('Идентификатор места.'),
            title: zod.string().describe('Название места.'),
            summary: zod.string().describe('Короткое описание для каталога.'),
            tags: zod.array(zod.string()).describe('Набор тегов для поиска и фильтрации.'),
            category: zod
              .enum(['pools', 'spa', 'cafe', 'hotels', 'workshops'])
              .describe('Категория места в каталоге.'),
            status: zod.enum(['active', 'hidden']).describe('Статус публикации места.'),
            popularityWeight: zod.number().describe('Вес популярности для сортировки.'),
          })
          .describe('Краткая карточка места, используемая в списках.'),
      )
      .describe('Элементы текущей страницы.'),
    total: zod.number().describe('Общее количество доступных элементов.'),
    page: zod.number().describe('Текущая страница.'),
    pageSize: zod.number().describe('Размер страницы.'),
  })
  .describe('Пагинированный список мест.');

export const ListFavorites401Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

/**
 * Добавляет место в избранное текущего пользователя.
 * @summary Add favorite
 */
export const AddFavoriteParams = zod.strictObject({
  placeId: zod.string().describe('Идентификатор места.'),
});

export const AddFavorite401Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

export const AddFavorite404Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

/**
 * Удаляет место из избранного текущего пользователя.
 * @summary Remove favorite
 */
export const RemoveFavoriteParams = zod.strictObject({
  placeId: zod.string().describe('Идентификатор места.'),
});

export const RemoveFavorite401Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');
