/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * Amazing EKB backend contract.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * @summary Current principal favorite places.
 */

export const favoritesList200ResponseTotalMin = 0;

export const FavoritesList200Response = zod.strictObject({
  items: zod.array(
    zod.strictObject({
      category: zod.strictObject({
        coverImageUrl: zod.string().nullable(),
        id: zod.string(),
        slug: zod.string(),
        title: zod.string(),
      }),
      coverImageUrl: zod.string().nullable(),
      id: zod.string(),
      slug: zod.string(),
      status: zod.enum(['active', 'hidden']),
      summary: zod.string(),
      tags: zod.array(zod.string()),
      title: zod.string(),
    }),
  ),
  page: zod.number().min(1),
  pageSize: zod.number().min(1),
  total: zod.number().min(favoritesList200ResponseTotalMin),
});

/**
 * @summary Place removed from favorites.
 */
export const FavoritesRemoveParams = zod.strictObject({
  placeId: zod.string(),
});

/**
 * @summary Place added to favorites.
 */
export const FavoritesAddParams = zod.strictObject({
  placeId: zod.string(),
});
