/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * MVP backend API (OpenAPI-first)
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * Аутентифицирует пользователя по email и паролю и возвращает пару access/refresh токенов.
 * @summary Login
 */
export const loginBodyPasswordMin = 8;

export const LoginBody = zod
  .strictObject({
    email: zod.email().describe('Email пользователя.'),
    password: zod.string().min(loginBodyPasswordMin).describe('Пароль пользователя.'),
  })
  .describe('Данные для входа пользователя по email и паролю.');

export const Login200Response = zod
  .strictObject({
    accessToken: zod.string().describe('JWT access token для авторизованных запросов.'),
    refreshToken: zod.string().describe('Refresh token для получения новой пары токенов.'),
    tokenType: zod.string().describe('Тип токена для заголовка `Authorization`.'),
    accessExpiresIn: zod
      .string()
      .optional()
      .describe('TTL access token в человекочитаемом формате.'),
  })
  .describe('Контракт успешной аутентификации.');

export const Login400Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

export const Login401Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

/**
 * Обновляет access/refresh токены по валидному refresh token.
 * @summary Refresh tokens
 */
export const RefreshTokensBody = zod
  .strictObject({
    refreshToken: zod
      .string()
      .describe('Refresh token, полученный при логине или предыдущем refresh.'),
  })
  .describe('Payload для перевыпуска access\/refresh токенов.');

export const RefreshTokens200Response = zod
  .strictObject({
    accessToken: zod.string().describe('JWT access token для авторизованных запросов.'),
    refreshToken: zod.string().describe('Refresh token для получения новой пары токенов.'),
    tokenType: zod.string().describe('Тип токена для заголовка `Authorization`.'),
    accessExpiresIn: zod
      .string()
      .optional()
      .describe('TTL access token в человекочитаемом формате.'),
  })
  .describe('Контракт успешной аутентификации.');

export const RefreshTokens400Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

export const RefreshTokens401Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

/**
 * Выполняет logout и отзывает переданный refresh token.
 * @summary Logout
 */
export const LogoutBody = zod
  .strictObject({
    refreshToken: zod.string().describe('Refresh token, который нужно отозвать.'),
  })
  .describe('Payload для logout и отзыва refresh token.');

export const Logout400Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

export const Logout401Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

/**
 * Возвращает публичный профиль текущего аутентифицированного пользователя.
 * @summary Get current user
 */
export const GetCurrentUser200Response = zod
  .strictObject({
    id: zod.string().describe('Идентификатор пользователя.'),
    email: zod.email().describe('Email пользователя.'),
    role: zod.enum(['admin', 'user']).describe('Роль пользователя в системе.'),
  })
  .describe('Публичный профиль текущего пользователя.');

export const GetCurrentUser401Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');
