/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * Amazing EKB backend contract.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * @summary Get the current session-bound CSRF token
 */
export const authGetCsrfToken200ResponseCsrfTokenMin = 43;
export const authGetCsrfToken200ResponseCsrfTokenMax = 43;

export const authGetCsrfToken200ResponseCsrfTokenRegExp = new RegExp('^[A-Za-z0-9_-]{43}$');

export const AuthGetCsrfToken200Response = zod.strictObject({
  csrfToken: zod
    .string()
    .min(authGetCsrfToken200ResponseCsrfTokenMin)
    .max(authGetCsrfToken200ResponseCsrfTokenMax)
    .regex(authGetCsrfToken200ResponseCsrfTokenRegExp),
});

/**
 * @summary Create a browser session
 */
export const authLoginBodyEmailMax = 254;

export const authLoginBodyPasswordMax = 1024;

export const AuthLoginBody = zod.strictObject({
  email: zod.email().max(authLoginBodyEmailMax),
  password: zod.string().min(1).max(authLoginBodyPasswordMax),
});

export const authLogin200ResponseCsrfTokenMin = 43;
export const authLogin200ResponseCsrfTokenMax = 43;

export const authLogin200ResponseCsrfTokenRegExp = new RegExp('^[A-Za-z0-9_-]{43}$');
export const authLogin200ResponseSessionPublicIdMin = 22;
export const authLogin200ResponseSessionPublicIdMax = 22;

export const authLogin200ResponseSessionPublicIdRegExp = new RegExp('^[A-Za-z0-9_-]{22}$');

export const AuthLogin200Response = zod.strictObject({
  csrfToken: zod
    .string()
    .min(authLogin200ResponseCsrfTokenMin)
    .max(authLogin200ResponseCsrfTokenMax)
    .regex(authLogin200ResponseCsrfTokenRegExp),
  session: zod.strictObject({
    absoluteExpiresAt: zod.iso.datetime({ offset: true }),
    publicId: zod
      .string()
      .min(authLogin200ResponseSessionPublicIdMin)
      .max(authLogin200ResponseSessionPublicIdMax)
      .regex(authLogin200ResponseSessionPublicIdRegExp),
  }),
});

/**
 * @summary Get the current authenticated identity
 */
export const authGetMe200ResponseNormalizedEmailMax = 254;

export const authGetMe200ResponsePermissionsItemRegExp = new RegExp(
  '^[a-z][a-z0-9]\*(?:\\.[a-z][a-z0-9]\*)+$',
);

export const AuthGetMe200Response = zod.strictObject({
  normalizedEmail: zod.email().max(authGetMe200ResponseNormalizedEmailMax),
  permissions: zod.array(zod.string().regex(authGetMe200ResponsePermissionsItemRegExp)),
  roleKeys: zod.array(zod.string()),
  userId: zod.uuid(),
});

/**
 * @summary Change the current account password
 */
export const authChangePasswordBodyCurrentPasswordMax = 1024;

export const authChangePasswordBodyNewPasswordMin = 12;
export const authChangePasswordBodyNewPasswordMax = 1024;

export const AuthChangePasswordBody = zod.strictObject({
  currentPassword: zod.string().min(1).max(authChangePasswordBodyCurrentPasswordMax),
  newPassword: zod
    .string()
    .min(authChangePasswordBodyNewPasswordMin)
    .max(authChangePasswordBodyNewPasswordMax),
});

export const AuthChangePassword200Response = zod.strictObject({
  cleanupComplete: zod
    .boolean()
    .describe('Whether best-effort Redis session cleanup completed after the durable mutation.'),
});

/**
 * @summary Revoke every browser session for the current user
 */
export const AuthLogoutAll200Response = zod.strictObject({
  cleanupComplete: zod
    .boolean()
    .describe('Whether best-effort Redis session cleanup completed after the durable mutation.'),
});

/**
 * @summary List browser sessions owned by the current user
 */
export const authListSessions200ResponseSessionsItemDeviceLabelMax = 256;

export const authListSessions200ResponseSessionsItemPublicIdMin = 22;
export const authListSessions200ResponseSessionsItemPublicIdMax = 22;

export const authListSessions200ResponseSessionsItemPublicIdRegExp = new RegExp(
  '^[A-Za-z0-9_-]{22}$',
);

export const AuthListSessions200Response = zod.strictObject({
  sessions: zod.array(
    zod.strictObject({
      absoluteExpiresAt: zod.iso.datetime({ offset: true }),
      createdAt: zod.iso.datetime({ offset: true }),
      current: zod.boolean(),
      deviceLabel: zod.string().max(authListSessions200ResponseSessionsItemDeviceLabelMax),
      lastSeenAt: zod.iso.datetime({ offset: true }),
      publicId: zod
        .string()
        .min(authListSessions200ResponseSessionsItemPublicIdMin)
        .max(authListSessions200ResponseSessionsItemPublicIdMax)
        .regex(authListSessions200ResponseSessionsItemPublicIdRegExp),
    }),
  ),
});

/**
 * @summary Revoke one owned browser session
 */
export const authRevokeSessionPathSessionIdMin = 22;
export const authRevokeSessionPathSessionIdMax = 22;

export const authRevokeSessionPathSessionIdRegExp = new RegExp('^[A-Za-z0-9_-]{22}$');

export const AuthRevokeSessionParams = zod.strictObject({
  sessionId: zod
    .string()
    .min(authRevokeSessionPathSessionIdMin)
    .max(authRevokeSessionPathSessionIdMax)
    .regex(authRevokeSessionPathSessionIdRegExp),
});
