/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * MVP backend API (OpenAPI-first)
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * Аутентифицирует пользователя по email и паролю, ставит access/refresh HttpOnly cookies и возвращает публичный профиль.
 * @summary Login
 */
export const LoginBody = zod
  .strictObject({
    email: zod.email().describe('Email пользователя.'),
    password: zod
      .string()
      .describe(
        'Пароль пользователя. Login не раскрывает password policy и возвращает generic credentials error для неверного пароля любой длины.',
      ),
  })
  .describe('Данные для входа пользователя по email и паролю.');

export const Login200Response = zod
  .strictObject({
    id: zod.string().describe('Идентификатор пользователя.'),
    email: zod.email().describe('Email пользователя.'),
    role: zod.enum(['admin', 'user']).describe('Роль пользователя в системе.'),
  })
  .describe('Публичный профиль текущего пользователя.');

export const Login400Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const Login401Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const Login429Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

/**
 * Обновляет access/refresh HttpOnly cookies по валидной refresh cookie.
 * @summary Refresh tokens
 */
export const RefreshTokens401Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const RefreshTokens429Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

/**
 * Возвращает публичный профиль текущего аутентифицированного пользователя.
 * @summary Get current user
 */
export const GetCurrentUser200Response = zod
  .strictObject({
    id: zod.string().describe('Идентификатор пользователя.'),
    email: zod.email().describe('Email пользователя.'),
    role: zod.enum(['admin', 'user']).describe('Роль пользователя в системе.'),
  })
  .describe('Публичный профиль текущего пользователя.');

export const GetCurrentUser401Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');
