/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * MVP backend API (OpenAPI-first)
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * Создаёт новое место в каталоге. Операция доступна только администратору.
 * @summary Create place
 */
export const createPlaceBodyPopularityWeightDefault = 0;

export const CreatePlaceBody = zod
  .strictObject({
    title: zod.string().describe('Название места.'),
    summary: zod.string().describe('Короткое описание места.'),
    tags: zod.array(zod.string()).describe('Теги для поиска и фильтрации.'),
    category: zod
      .enum(['pools', 'spa', 'cafe', 'hotels', 'workshops'])
      .describe('Категория места в каталоге.'),
    popularityWeight: zod
      .number()
      .default(createPlaceBodyPopularityWeightDefault)
      .describe('Начальный вес популярности.'),
  })
  .describe('Payload создания нового места.');

export const CreatePlace201Response = zod
  .strictObject({
    id: zod.string().describe('Идентификатор места.'),
    title: zod.string().describe('Название места.'),
    summary: zod.string().describe('Короткое описание для каталога.'),
    tags: zod.array(zod.string()).describe('Набор тегов для поиска и фильтрации.'),
    category: zod
      .enum(['pools', 'spa', 'cafe', 'hotels', 'workshops'])
      .describe('Категория места в каталоге.'),
    status: zod.enum(['active', 'hidden']).describe('Статус публикации места.'),
    popularityWeight: zod.number().describe('Вес популярности для сортировки.'),
  })
  .describe('Краткая карточка места, используемая в списках.');

export const CreatePlace400Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

export const CreatePlace401Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

export const CreatePlace403Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

/**
 * Частично обновляет место по идентификатору. Операция доступна только администратору.
 * @summary Update place
 */
export const UpdatePlaceParams = zod.strictObject({
  placeId: zod.string().describe('Идентификатор места.'),
});

export const UpdatePlaceBody = zod
  .strictObject({
    title: zod.string().optional().describe('Новое название места.'),
    summary: zod.string().optional().describe('Обновлённое краткое описание.'),
    tags: zod.array(zod.string()).optional().describe('Новый набор тегов.'),
    category: zod
      .enum(['pools', 'spa', 'cafe', 'hotels', 'workshops'])
      .optional()
      .describe('Категория места в каталоге.'),
    popularityWeight: zod.number().optional().describe('Обновлённый вес популярности.'),
  })
  .describe('Payload частичного обновления места.');

export const UpdatePlace200Response = zod
  .strictObject({
    id: zod.string().describe('Идентификатор места.'),
    title: zod.string().describe('Название места.'),
    summary: zod.string().describe('Короткое описание для каталога.'),
    tags: zod.array(zod.string()).describe('Набор тегов для поиска и фильтрации.'),
    category: zod
      .enum(['pools', 'spa', 'cafe', 'hotels', 'workshops'])
      .describe('Категория места в каталоге.'),
    status: zod.enum(['active', 'hidden']).describe('Статус публикации места.'),
    popularityWeight: zod.number().describe('Вес популярности для сортировки.'),
  })
  .describe('Краткая карточка места, используемая в списках.');

export const UpdatePlace400Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

export const UpdatePlace401Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

export const UpdatePlace403Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

export const UpdatePlace404Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

/**
 * Меняет статус публикации места. Операция доступна только администратору.
 * @summary Update place status
 */
export const UpdatePlaceStatusParams = zod.strictObject({
  placeId: zod.string().describe('Идентификатор места.'),
});

export const UpdatePlaceStatusBody = zod
  .strictObject({
    status: zod.enum(['active', 'hidden']).describe('Статус публикации места.'),
  })
  .describe('Payload изменения статуса места.');

export const UpdatePlaceStatus200Response = zod
  .strictObject({
    id: zod.string().describe('Идентификатор места.'),
    title: zod.string().describe('Название места.'),
    summary: zod.string().describe('Короткое описание для каталога.'),
    tags: zod.array(zod.string()).describe('Набор тегов для поиска и фильтрации.'),
    category: zod
      .enum(['pools', 'spa', 'cafe', 'hotels', 'workshops'])
      .describe('Категория места в каталоге.'),
    status: zod.enum(['active', 'hidden']).describe('Статус публикации места.'),
    popularityWeight: zod.number().describe('Вес популярности для сортировки.'),
  })
  .describe('Краткая карточка места, используемая в списках.');

export const UpdatePlaceStatus400Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

export const UpdatePlaceStatus401Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

export const UpdatePlaceStatus403Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

export const UpdatePlaceStatus404Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

/**
 * Создаёт новый материал для указанного места. Операция доступна только администратору.
 * @summary Create material for place
 */
export const CreatePlaceMaterialParams = zod.strictObject({
  placeId: zod.string().describe('Идентификатор места.'),
});

export const CreatePlaceMaterialBody = zod
  .strictObject({
    platform: zod
      .enum(['dzen', 'telegram', 'instagram'])
      .describe('Платформа, на которой опубликован материал.'),
    type: zod.enum(['post', 'reel', 'video']).describe('Тип материала.'),
    title: zod.string().describe('Заголовок материала.'),
    publishedAt: zod.iso.datetime({}).describe('Момент публикации материала.'),
    durationSec: zod.number().nullish().describe('Длительность в секундах для видеоформатов.'),
    url: zod.url().describe('Публичная ссылка на материал.'),
  })
  .describe('Payload создания нового материала для места.');

export const CreatePlaceMaterial201Response = zod
  .strictObject({
    id: zod.string().describe('Идентификатор материала.'),
    placeId: zod.string().describe('Идентификатор места, к которому относится материал.'),
    platform: zod
      .enum(['dzen', 'telegram', 'instagram'])
      .describe('Платформа, на которой опубликован материал.'),
    type: zod.enum(['post', 'reel', 'video']).describe('Тип материала.'),
    title: zod.string().describe('Заголовок материала.'),
    publishedAt: zod.iso.datetime({}).describe('Дата и время публикации материала.'),
    durationSec: zod.number().nullable().describe('Длительность в секундах для видеоформатов.'),
    url: zod.url().describe('Публичная ссылка на материал.'),
  })
  .describe('Материал, связанный с местом.');

export const CreatePlaceMaterial400Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

export const CreatePlaceMaterial401Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

export const CreatePlaceMaterial403Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

export const CreatePlaceMaterial404Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

/**
 * Частично обновляет материал по идентификатору. Операция доступна только администратору.
 * @summary Update material
 */
export const UpdateMaterialParams = zod.strictObject({
  materialId: zod.string().describe('Идентификатор материала.'),
});

export const UpdateMaterialBody = zod
  .strictObject({
    platform: zod
      .enum(['dzen', 'telegram', 'instagram'])
      .optional()
      .describe('Платформа, на которой опубликован материал.'),
    type: zod.enum(['post', 'reel', 'video']).optional().describe('Тип материала.'),
    title: zod.string().optional().describe('Новый заголовок материала.'),
    publishedAt: zod.iso.datetime({}).optional().describe('Новая дата публикации.'),
    durationSec: zod.number().nullish().describe('Новая длительность в секундах.'),
    url: zod.url().optional().describe('Новая публичная ссылка на материал.'),
  })
  .describe('Payload частичного обновления материала.');

export const UpdateMaterial200Response = zod
  .strictObject({
    id: zod.string().describe('Идентификатор материала.'),
    placeId: zod.string().describe('Идентификатор места, к которому относится материал.'),
    platform: zod
      .enum(['dzen', 'telegram', 'instagram'])
      .describe('Платформа, на которой опубликован материал.'),
    type: zod.enum(['post', 'reel', 'video']).describe('Тип материала.'),
    title: zod.string().describe('Заголовок материала.'),
    publishedAt: zod.iso.datetime({}).describe('Дата и время публикации материала.'),
    durationSec: zod.number().nullable().describe('Длительность в секундах для видеоформатов.'),
    url: zod.url().describe('Публичная ссылка на материал.'),
  })
  .describe('Материал, связанный с местом.');

export const UpdateMaterial400Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

export const UpdateMaterial401Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

export const UpdateMaterial403Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

export const UpdateMaterial404Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

/**
 * Назначает закреплённый материал для места. Операция доступна только администратору.
 * @summary Set pinned material for place
 */
export const SetPinnedMaterialParams = zod.strictObject({
  placeId: zod.string().describe('Идентификатор места.'),
});

export const SetPinnedMaterialBody = zod
  .strictObject({
    materialId: zod.string().describe('Идентификатор материала, который нужно закрепить.'),
  })
  .describe('Payload назначения закреплённого материала для места.');

export const SetPinnedMaterial200Response = zod
  .strictObject({
    id: zod.string().describe('Идентификатор места.'),
    title: zod.string().describe('Название места.'),
    summary: zod.string().describe('Короткое описание для каталога.'),
    tags: zod.array(zod.string()).describe('Набор тегов для поиска и фильтрации.'),
    category: zod
      .enum(['pools', 'spa', 'cafe', 'hotels', 'workshops'])
      .describe('Категория места в каталоге.'),
    status: zod.enum(['active', 'hidden']).describe('Статус публикации места.'),
    popularityWeight: zod.number().describe('Вес популярности для сортировки.'),
    pinnedMaterial: zod
      .strictObject({
        id: zod.string().describe('Идентификатор материала.'),
        placeId: zod.string().describe('Идентификатор места, к которому относится материал.'),
        platform: zod
          .enum(['dzen', 'telegram', 'instagram'])
          .describe('Платформа, на которой опубликован материал.'),
        type: zod.enum(['post', 'reel', 'video']).describe('Тип материала.'),
        title: zod.string().describe('Заголовок материала.'),
        publishedAt: zod.iso.datetime({}).describe('Дата и время публикации материала.'),
        durationSec: zod.number().nullable().describe('Длительность в секундах для видеоформатов.'),
        url: zod.url().describe('Публичная ссылка на материал.'),
      })
      .describe('Материал, связанный с местом.')
      .nullable()
      .describe('Закреплённый материал места, если он назначен.'),
    counters: zod
      .strictObject({
        dzen: zod.number(),
        telegram: zod.number(),
        instagram: zod.number(),
      })
      .describe('Количество материалов по платформам.'),
  })
  .describe('Детальная карточка места с pinned material и счетчиками по платформам.');

export const SetPinnedMaterial400Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

export const SetPinnedMaterial401Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

export const SetPinnedMaterial403Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');

export const SetPinnedMaterial404Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');
