/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * MVP backend API (OpenAPI-first)
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * Возвращает административный список мест с пагинацией и опциональной фильтрацией по статусу. Если `status` не указан, возвращаются и активные, и скрытые места.
 * @summary List admin places
 */
export const listAdminPlacesQueryPageDefault = 1;
export const listAdminPlacesQueryPageMax = 1000;

export const listAdminPlacesQueryPageSizeDefault = 20;
export const listAdminPlacesQueryPageSizeMax = 100;

export const ListAdminPlacesQueryParams = zod.strictObject({
  page: zod
    .number()
    .min(1)
    .max(listAdminPlacesQueryPageMax)
    .default(listAdminPlacesQueryPageDefault)
    .describe('Номер страницы пагинации. Допустимый диапазон от `1` до `1000`.'),
  pageSize: zod
    .number()
    .min(1)
    .max(listAdminPlacesQueryPageSizeMax)
    .default(listAdminPlacesQueryPageSizeDefault)
    .describe('Размер страницы. Допустимый диапазон от `1` до `100`.'),
  status: zod
    .enum(['active', 'hidden'])
    .optional()
    .describe('Фильтр по статусу места. Если параметр отсутствует, возвращаются все статусы.'),
});

export const ListAdminPlaces200Response = zod
  .strictObject({
    items: zod
      .array(
        zod
          .strictObject({
            id: zod.string().describe('Идентификатор места.'),
            title: zod.string().describe('Название места.'),
            summary: zod.string().describe('Короткое описание для каталога.'),
            tags: zod.array(zod.string()).describe('Набор тегов для поиска и фильтрации.'),
            category: zod
              .enum(['pools', 'spa', 'cafe', 'hotels', 'workshops'])
              .describe('Категория места в каталоге.'),
            status: zod.enum(['active', 'hidden']).describe('Статус публикации места.'),
            popularityWeight: zod.number().describe('Вес популярности для сортировки.'),
            coverImageUrl: zod
              .string()
              .nullable()
              .describe(
                'Публичный cover-фото места. Если фото отсутствует или не должно отдаться публично, возвращается `null`.',
              ),
          })
          .describe('Краткая карточка места, используемая в списках.'),
      )
      .describe('Элементы текущей страницы.'),
    total: zod.number().describe('Общее количество доступных элементов.'),
    page: zod.number().describe('Текущая страница.'),
    pageSize: zod.number().describe('Размер страницы.'),
  })
  .describe('Пагинированный список мест.');

export const ListAdminPlaces400Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const ListAdminPlaces401Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const ListAdminPlaces403Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

/**
 * Создаёт новое место в каталоге. Операция доступна только администратору.
 * @summary Create place
 */
export const CreatePlaceBody = zod
  .strictObject({
    title: zod.string().describe('Название места.'),
    summary: zod
      .string()
      .optional()
      .describe('Короткое описание места. Если поле не передано, backend сохранит пустую строку.'),
    tags: zod
      .array(zod.string())
      .optional()
      .describe(
        'Теги для поиска и фильтрации. Если поле не передано, backend сохранит пустой массив.',
      ),
    category: zod
      .enum(['pools', 'spa', 'cafe', 'hotels', 'workshops'])
      .describe('Категория места в каталоге.'),
    popularityWeight: zod
      .number()
      .optional()
      .describe('Начальный вес популярности. Если поле не передано, backend сохранит 0.'),
  })
  .describe('Payload создания нового места.');

export const CreatePlace201Response = zod
  .strictObject({
    id: zod.string().describe('Идентификатор места.'),
    title: zod.string().describe('Название места.'),
    summary: zod.string().describe('Короткое описание для каталога.'),
    tags: zod.array(zod.string()).describe('Набор тегов для поиска и фильтрации.'),
    category: zod
      .enum(['pools', 'spa', 'cafe', 'hotels', 'workshops'])
      .describe('Категория места в каталоге.'),
    status: zod.enum(['active', 'hidden']).describe('Статус публикации места.'),
    popularityWeight: zod.number().describe('Вес популярности для сортировки.'),
    coverImageUrl: zod
      .string()
      .nullable()
      .describe(
        'Публичный cover-фото места. Если фото отсутствует или не должно отдаться публично, возвращается `null`.',
      ),
  })
  .describe('Краткая карточка места, используемая в списках.');

export const CreatePlace400Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const CreatePlace401Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const CreatePlace403Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

/**
 * Возвращает детальную карточку места для администратора независимо от публичного статуса места.
 * @summary Get admin place details
 */
export const GetAdminPlaceDetailParams = zod.strictObject({
  placeId: zod.string().describe('Идентификатор места.'),
});

export const GetAdminPlaceDetail200Response = zod
  .strictObject({
    id: zod.string().describe('Идентификатор места.'),
    title: zod.string().describe('Название места.'),
    summary: zod.string().describe('Короткое описание для каталога.'),
    tags: zod.array(zod.string()).describe('Набор тегов для поиска и фильтрации.'),
    category: zod
      .enum(['pools', 'spa', 'cafe', 'hotels', 'workshops'])
      .describe('Категория места в каталоге.'),
    status: zod.enum(['active', 'hidden']).describe('Статус публикации места.'),
    popularityWeight: zod.number().describe('Вес популярности для сортировки.'),
    coverImageUrl: zod
      .string()
      .nullable()
      .describe(
        'Публичный cover-фото места. Если фото отсутствует или не должно отдаться публично, возвращается `null`.',
      ),
    counters: zod
      .strictObject({
        dzen: zod.number(),
        telegram: zod.number(),
        instagram: zod.number(),
      })
      .describe('Количество материалов по платформам.'),
  })
  .describe('Краткая публичная карточка места со счетчиками материалов по платформам.')
  .and(
    zod.strictObject({
      pinnedMaterial: zod
        .strictObject({
          id: zod.string().describe('Идентификатор материала.'),
          placeId: zod.string().describe('Идентификатор места, к которому относится материал.'),
          platform: zod
            .enum(['dzen', 'telegram', 'instagram'])
            .describe('Платформа, на которой опубликован материал.'),
          type: zod.enum(['post', 'reel', 'video']).describe('Тип материала.'),
          title: zod.string().describe('Заголовок материала.'),
          publishedAt: zod.iso
            .datetime({ offset: true })
            .describe('Дата и время публикации материала.'),
          durationSec: zod
            .number()
            .nullable()
            .describe('Длительность в секундах для видеоформатов.'),
          url: zod
            .url()
            .describe(
              'Публичная ссылка на материал. Допускаются только абсолютные http\/https URL.',
            ),
          redirectUrl: zod
            .string()
            .nullish()
            .describe(
              'Same-origin redirect URL для публичного открытия материала без прямого внешнего href. Поле заполняется только для публично безопасных target URL.',
            ),
        })
        .describe('Материал, связанный с местом.')
        .nullable()
        .describe('Закреплённый материал места, если он назначен.'),
    }),
  )
  .describe('Детальная карточка места с pinned material и счетчиками по платформам.');

export const GetAdminPlaceDetail401Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const GetAdminPlaceDetail403Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const GetAdminPlaceDetail404Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

/**
 * Частично обновляет место по идентификатору. Операция доступна только администратору.
 * @summary Update place
 */
export const UpdatePlaceParams = zod.strictObject({
  placeId: zod.string().describe('Идентификатор места.'),
});

export const UpdatePlaceBody = zod
  .strictObject({
    title: zod.string().optional().describe('Новое название места.'),
    summary: zod.string().optional().describe('Обновлённое краткое описание.'),
    tags: zod.array(zod.string()).optional().describe('Новый набор тегов.'),
    category: zod
      .enum(['pools', 'spa', 'cafe', 'hotels', 'workshops'])
      .optional()
      .describe('Категория места в каталоге.'),
    popularityWeight: zod.number().optional().describe('Обновлённый вес популярности.'),
  })
  .describe('Payload частичного обновления места.');

export const UpdatePlace200Response = zod
  .strictObject({
    id: zod.string().describe('Идентификатор места.'),
    title: zod.string().describe('Название места.'),
    summary: zod.string().describe('Короткое описание для каталога.'),
    tags: zod.array(zod.string()).describe('Набор тегов для поиска и фильтрации.'),
    category: zod
      .enum(['pools', 'spa', 'cafe', 'hotels', 'workshops'])
      .describe('Категория места в каталоге.'),
    status: zod.enum(['active', 'hidden']).describe('Статус публикации места.'),
    popularityWeight: zod.number().describe('Вес популярности для сортировки.'),
    coverImageUrl: zod
      .string()
      .nullable()
      .describe(
        'Публичный cover-фото места. Если фото отсутствует или не должно отдаться публично, возвращается `null`.',
      ),
  })
  .describe('Краткая карточка места, используемая в списках.');

export const UpdatePlace400Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const UpdatePlace401Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const UpdatePlace403Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const UpdatePlace404Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

/**
 * Меняет статус публикации места. Операция доступна только администратору.
 * @summary Update place status
 */
export const UpdatePlaceStatusParams = zod.strictObject({
  placeId: zod.string().describe('Идентификатор места.'),
});

export const UpdatePlaceStatusBody = zod
  .strictObject({
    status: zod.enum(['active', 'hidden']).describe('Статус публикации места.'),
  })
  .describe('Payload изменения статуса места.');

export const UpdatePlaceStatus200Response = zod
  .strictObject({
    id: zod.string().describe('Идентификатор места.'),
    title: zod.string().describe('Название места.'),
    summary: zod.string().describe('Короткое описание для каталога.'),
    tags: zod.array(zod.string()).describe('Набор тегов для поиска и фильтрации.'),
    category: zod
      .enum(['pools', 'spa', 'cafe', 'hotels', 'workshops'])
      .describe('Категория места в каталоге.'),
    status: zod.enum(['active', 'hidden']).describe('Статус публикации места.'),
    popularityWeight: zod.number().describe('Вес популярности для сортировки.'),
    coverImageUrl: zod
      .string()
      .nullable()
      .describe(
        'Публичный cover-фото места. Если фото отсутствует или не должно отдаться публично, возвращается `null`.',
      ),
  })
  .describe('Краткая карточка места, используемая в списках.');

export const UpdatePlaceStatus400Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const UpdatePlaceStatus401Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const UpdatePlaceStatus403Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const UpdatePlaceStatus404Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

/**
 * Загружает или заменяет cover-фото места. Операция доступна только администратору.
 * @summary Upload place cover photo
 */
export const UploadPlaceCoverPhotoParams = zod.strictObject({
  placeId: zod.string().describe('Идентификатор места.'),
});

export const UploadPlaceCoverPhotoBody = zod
  .strictObject({
    photo: zod.instanceof(File),
  })
  .describe('Multipart payload для загрузки cover-фото места.');

export const UploadPlaceCoverPhoto200Response = zod
  .strictObject({
    id: zod.string().describe('Идентификатор места.'),
    title: zod.string().describe('Название места.'),
    summary: zod.string().describe('Короткое описание для каталога.'),
    tags: zod.array(zod.string()).describe('Набор тегов для поиска и фильтрации.'),
    category: zod
      .enum(['pools', 'spa', 'cafe', 'hotels', 'workshops'])
      .describe('Категория места в каталоге.'),
    status: zod.enum(['active', 'hidden']).describe('Статус публикации места.'),
    popularityWeight: zod.number().describe('Вес популярности для сортировки.'),
    coverImageUrl: zod
      .string()
      .nullable()
      .describe(
        'Публичный cover-фото места. Если фото отсутствует или не должно отдаться публично, возвращается `null`.',
      ),
  })
  .describe('Краткая карточка места, используемая в списках.');

export const UploadPlaceCoverPhoto400Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const UploadPlaceCoverPhoto401Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const UploadPlaceCoverPhoto403Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const UploadPlaceCoverPhoto404Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

/**
 * Возвращает до 100 материалов указанного места для администратора, включая скрытые места.
 * @summary List admin place materials
 */
export const ListAdminPlaceMaterialsParams = zod.strictObject({
  placeId: zod.string().describe('Идентификатор места.'),
});

export const ListAdminPlaceMaterialsQueryParams = zod.strictObject({
  platform: zod
    .enum(['dzen', 'telegram', 'instagram'])
    .optional()
    .describe('Фильтр по платформе публикации материала.'),
});

export const ListAdminPlaceMaterials200Response = zod
  .strictObject({
    items: zod
      .array(
        zod
          .strictObject({
            id: zod.string().describe('Идентификатор материала.'),
            placeId: zod.string().describe('Идентификатор места, к которому относится материал.'),
            platform: zod
              .enum(['dzen', 'telegram', 'instagram'])
              .describe('Платформа, на которой опубликован материал.'),
            type: zod.enum(['post', 'reel', 'video']).describe('Тип материала.'),
            title: zod.string().describe('Заголовок материала.'),
            publishedAt: zod.iso
              .datetime({ offset: true })
              .describe('Дата и время публикации материала.'),
            durationSec: zod
              .number()
              .nullable()
              .describe('Длительность в секундах для видеоформатов.'),
            url: zod
              .url()
              .describe(
                'Публичная ссылка на материал. Допускаются только абсолютные http\/https URL.',
              ),
            redirectUrl: zod
              .string()
              .nullish()
              .describe(
                'Same-origin redirect URL для публичного открытия материала без прямого внешнего href. Поле заполняется только для публично безопасных target URL.',
              ),
          })
          .describe('Материал, связанный с местом.'),
      )
      .describe('Материалы места в стабильном порядке отображения.'),
  })
  .describe('Ограниченный список материалов места.');

export const ListAdminPlaceMaterials400Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const ListAdminPlaceMaterials401Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const ListAdminPlaceMaterials403Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const ListAdminPlaceMaterials404Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

/**
 * Создаёт новый материал для указанного места. Операция доступна только администратору.
 * @summary Create material for place
 */
export const CreatePlaceMaterialParams = zod.strictObject({
  placeId: zod.string().describe('Идентификатор места.'),
});

export const CreatePlaceMaterialBody = zod
  .strictObject({
    platform: zod
      .enum(['dzen', 'telegram', 'instagram'])
      .describe('Платформа, на которой опубликован материал.'),
    type: zod.enum(['post', 'reel', 'video']).describe('Тип материала.'),
    title: zod.string().describe('Заголовок материала.'),
    publishedAt: zod.iso.datetime({ offset: true }).describe('Момент публикации материала.'),
    durationSec: zod.number().nullish().describe('Длительность в секундах для видеоформатов.'),
    url: zod
      .url()
      .describe('Публичная ссылка на материал. Допускаются только абсолютные http\/https URL.'),
  })
  .describe('Payload создания нового материала для места.');

export const CreatePlaceMaterial201Response = zod
  .strictObject({
    id: zod.string().describe('Идентификатор материала.'),
    placeId: zod.string().describe('Идентификатор места, к которому относится материал.'),
    platform: zod
      .enum(['dzen', 'telegram', 'instagram'])
      .describe('Платформа, на которой опубликован материал.'),
    type: zod.enum(['post', 'reel', 'video']).describe('Тип материала.'),
    title: zod.string().describe('Заголовок материала.'),
    publishedAt: zod.iso.datetime({ offset: true }).describe('Дата и время публикации материала.'),
    durationSec: zod.number().nullable().describe('Длительность в секундах для видеоформатов.'),
    url: zod
      .url()
      .describe('Публичная ссылка на материал. Допускаются только абсолютные http\/https URL.'),
    redirectUrl: zod
      .string()
      .nullish()
      .describe(
        'Same-origin redirect URL для публичного открытия материала без прямого внешнего href. Поле заполняется только для публично безопасных target URL.',
      ),
  })
  .describe('Материал, связанный с местом.');

export const CreatePlaceMaterial400Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const CreatePlaceMaterial401Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const CreatePlaceMaterial403Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const CreatePlaceMaterial404Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

/**
 * Частично обновляет материал по идентификатору. Операция доступна только администратору.
 * @summary Update material
 */
export const UpdateMaterialParams = zod.strictObject({
  materialId: zod.string().describe('Идентификатор материала.'),
});

export const UpdateMaterialBody = zod
  .strictObject({
    platform: zod
      .enum(['dzen', 'telegram', 'instagram'])
      .optional()
      .describe('Платформа, на которой опубликован материал.'),
    type: zod.enum(['post', 'reel', 'video']).optional().describe('Тип материала.'),
    title: zod.string().optional().describe('Новый заголовок материала.'),
    publishedAt: zod.iso.datetime({ offset: true }).optional().describe('Новая дата публикации.'),
    durationSec: zod.number().nullish().describe('Новая длительность в секундах.'),
    url: zod
      .url()
      .optional()
      .describe(
        'Новая публичная ссылка на материал. Допускаются только абсолютные http\/https URL.',
      ),
  })
  .describe('Payload частичного обновления материала.');

export const UpdateMaterial200Response = zod
  .strictObject({
    id: zod.string().describe('Идентификатор материала.'),
    placeId: zod.string().describe('Идентификатор места, к которому относится материал.'),
    platform: zod
      .enum(['dzen', 'telegram', 'instagram'])
      .describe('Платформа, на которой опубликован материал.'),
    type: zod.enum(['post', 'reel', 'video']).describe('Тип материала.'),
    title: zod.string().describe('Заголовок материала.'),
    publishedAt: zod.iso.datetime({ offset: true }).describe('Дата и время публикации материала.'),
    durationSec: zod.number().nullable().describe('Длительность в секундах для видеоформатов.'),
    url: zod
      .url()
      .describe('Публичная ссылка на материал. Допускаются только абсолютные http\/https URL.'),
    redirectUrl: zod
      .string()
      .nullish()
      .describe(
        'Same-origin redirect URL для публичного открытия материала без прямого внешнего href. Поле заполняется только для публично безопасных target URL.',
      ),
  })
  .describe('Материал, связанный с местом.');

export const UpdateMaterial400Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const UpdateMaterial401Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const UpdateMaterial403Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const UpdateMaterial404Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

/**
 * Назначает закреплённый материал для места. Операция доступна только администратору.
 * @summary Set pinned material for place
 */
export const SetPinnedMaterialParams = zod.strictObject({
  placeId: zod.string().describe('Идентификатор места.'),
});

export const SetPinnedMaterialBody = zod
  .strictObject({
    materialId: zod.string().describe('Идентификатор материала, который нужно закрепить.'),
  })
  .describe('Payload назначения закреплённого материала для места.');

export const SetPinnedMaterial200Response = zod
  .strictObject({
    id: zod.string().describe('Идентификатор места.'),
    title: zod.string().describe('Название места.'),
    summary: zod.string().describe('Короткое описание для каталога.'),
    tags: zod.array(zod.string()).describe('Набор тегов для поиска и фильтрации.'),
    category: zod
      .enum(['pools', 'spa', 'cafe', 'hotels', 'workshops'])
      .describe('Категория места в каталоге.'),
    status: zod.enum(['active', 'hidden']).describe('Статус публикации места.'),
    popularityWeight: zod.number().describe('Вес популярности для сортировки.'),
    coverImageUrl: zod
      .string()
      .nullable()
      .describe(
        'Публичный cover-фото места. Если фото отсутствует или не должно отдаться публично, возвращается `null`.',
      ),
    counters: zod
      .strictObject({
        dzen: zod.number(),
        telegram: zod.number(),
        instagram: zod.number(),
      })
      .describe('Количество материалов по платформам.'),
  })
  .describe('Краткая публичная карточка места со счетчиками материалов по платформам.')
  .and(
    zod.strictObject({
      pinnedMaterial: zod
        .strictObject({
          id: zod.string().describe('Идентификатор материала.'),
          placeId: zod.string().describe('Идентификатор места, к которому относится материал.'),
          platform: zod
            .enum(['dzen', 'telegram', 'instagram'])
            .describe('Платформа, на которой опубликован материал.'),
          type: zod.enum(['post', 'reel', 'video']).describe('Тип материала.'),
          title: zod.string().describe('Заголовок материала.'),
          publishedAt: zod.iso
            .datetime({ offset: true })
            .describe('Дата и время публикации материала.'),
          durationSec: zod
            .number()
            .nullable()
            .describe('Длительность в секундах для видеоформатов.'),
          url: zod
            .url()
            .describe(
              'Публичная ссылка на материал. Допускаются только абсолютные http\/https URL.',
            ),
          redirectUrl: zod
            .string()
            .nullish()
            .describe(
              'Same-origin redirect URL для публичного открытия материала без прямого внешнего href. Поле заполняется только для публично безопасных target URL.',
            ),
        })
        .describe('Материал, связанный с местом.')
        .nullable()
        .describe('Закреплённый материал места, если он назначен.'),
    }),
  )
  .describe('Детальная карточка места с pinned material и счетчиками по платформам.');

export const SetPinnedMaterial400Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const SetPinnedMaterial401Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const SetPinnedMaterial403Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const SetPinnedMaterial404Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

/**
 * Снимает закреплённый материал с места. Операция доступна только администратору.
 * @summary Clear pinned material for place
 */
export const ClearPinnedMaterialParams = zod.strictObject({
  placeId: zod.string().describe('Идентификатор места.'),
});

export const ClearPinnedMaterial200Response = zod
  .strictObject({
    id: zod.string().describe('Идентификатор места.'),
    title: zod.string().describe('Название места.'),
    summary: zod.string().describe('Короткое описание для каталога.'),
    tags: zod.array(zod.string()).describe('Набор тегов для поиска и фильтрации.'),
    category: zod
      .enum(['pools', 'spa', 'cafe', 'hotels', 'workshops'])
      .describe('Категория места в каталоге.'),
    status: zod.enum(['active', 'hidden']).describe('Статус публикации места.'),
    popularityWeight: zod.number().describe('Вес популярности для сортировки.'),
    coverImageUrl: zod
      .string()
      .nullable()
      .describe(
        'Публичный cover-фото места. Если фото отсутствует или не должно отдаться публично, возвращается `null`.',
      ),
    counters: zod
      .strictObject({
        dzen: zod.number(),
        telegram: zod.number(),
        instagram: zod.number(),
      })
      .describe('Количество материалов по платформам.'),
  })
  .describe('Краткая публичная карточка места со счетчиками материалов по платформам.')
  .and(
    zod.strictObject({
      pinnedMaterial: zod
        .strictObject({
          id: zod.string().describe('Идентификатор материала.'),
          placeId: zod.string().describe('Идентификатор места, к которому относится материал.'),
          platform: zod
            .enum(['dzen', 'telegram', 'instagram'])
            .describe('Платформа, на которой опубликован материал.'),
          type: zod.enum(['post', 'reel', 'video']).describe('Тип материала.'),
          title: zod.string().describe('Заголовок материала.'),
          publishedAt: zod.iso
            .datetime({ offset: true })
            .describe('Дата и время публикации материала.'),
          durationSec: zod
            .number()
            .nullable()
            .describe('Длительность в секундах для видеоформатов.'),
          url: zod
            .url()
            .describe(
              'Публичная ссылка на материал. Допускаются только абсолютные http\/https URL.',
            ),
          redirectUrl: zod
            .string()
            .nullish()
            .describe(
              'Same-origin redirect URL для публичного открытия материала без прямого внешнего href. Поле заполняется только для публично безопасных target URL.',
            ),
        })
        .describe('Материал, связанный с местом.')
        .nullable()
        .describe('Закреплённый материал места, если он назначен.'),
    }),
  )
  .describe('Детальная карточка места с pinned material и счетчиками по платформам.');

export const ClearPinnedMaterial401Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const ClearPinnedMaterial403Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const ClearPinnedMaterial404Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');
