/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * Amazing EKB backend contract.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * @summary Administrative collection list.
 */
export const adminCollectionsList200ResponseItemsItemActivePlaceCountMin = 0;

export const adminCollectionsList200ResponseItemsItemHiddenPlaceCountMin = 0;

export const adminCollectionsList200ResponseItemsItemPositionMin = 0;

export const AdminCollectionsList200Response = zod.strictObject({
  items: zod.array(
    zod.strictObject({
      activePlaceCount: zod
        .number()
        .min(adminCollectionsList200ResponseItemsItemActivePlaceCountMin),
      coverImageUrl: zod.string().nullable(),
      createdAt: zod.iso.datetime({ offset: true }),
      description: zod.string().nullable(),
      hiddenPlaceCount: zod
        .number()
        .min(adminCollectionsList200ResponseItemsItemHiddenPlaceCountMin),
      id: zod.string(),
      position: zod.number().min(adminCollectionsList200ResponseItemsItemPositionMin),
      slug: zod.string(),
      status: zod.enum(['draft', 'active']),
      title: zod.string(),
      updatedAt: zod.iso.datetime({ offset: true }),
    }),
  ),
});

/**
 * @summary Created draft collection.
 */
export const adminCollectionsCreateBodyDescriptionMax = 10000;

export const adminCollectionsCreateBodySlugRegExp = new RegExp('^[a-z0-9]+(?:-[a-z0-9]+)\*$');

export const AdminCollectionsCreateBody = zod.strictObject({
  description: zod.string().max(adminCollectionsCreateBodyDescriptionMax).nullish(),
  slug: zod.string().min(1).regex(adminCollectionsCreateBodySlugRegExp).optional(),
  title: zod.string().min(1),
});

export const adminCollectionsCreate201ResponseActivePlaceCountMin = 0;

export const adminCollectionsCreate201ResponseHiddenPlaceCountMin = 0;

export const adminCollectionsCreate201ResponsePositionMin = 0;

export const AdminCollectionsCreate201Response = zod.strictObject({
  activePlaceCount: zod.number().min(adminCollectionsCreate201ResponseActivePlaceCountMin),
  coverImageUrl: zod.string().nullable(),
  createdAt: zod.iso.datetime({ offset: true }),
  description: zod.string().nullable(),
  hiddenPlaceCount: zod.number().min(adminCollectionsCreate201ResponseHiddenPlaceCountMin),
  id: zod.string(),
  position: zod.number().min(adminCollectionsCreate201ResponsePositionMin),
  slug: zod.string(),
  status: zod.enum(['draft', 'active']),
  title: zod.string(),
  updatedAt: zod.iso.datetime({ offset: true }),
});

/**
 * @summary Deleted collection.
 */
export const AdminCollectionsDeleteParams = zod.strictObject({
  collectionId: zod.string(),
});

/**
 * @summary Administrative collection detail.
 */
export const AdminCollectionsGetParams = zod.strictObject({
  collectionId: zod.string(),
});

export const adminCollectionsGet200ResponseActivePlaceCountMin = 0;

export const adminCollectionsGet200ResponseHiddenPlaceCountMin = 0;

export const adminCollectionsGet200ResponsePlacesItemPositionMin = 0;

export const adminCollectionsGet200ResponsePositionMin = 0;

export const AdminCollectionsGet200Response = zod.strictObject({
  activePlaceCount: zod.number().min(adminCollectionsGet200ResponseActivePlaceCountMin),
  coverImageUrl: zod.string().nullable(),
  createdAt: zod.iso.datetime({ offset: true }),
  description: zod.string().nullable(),
  hiddenPlaceCount: zod.number().min(adminCollectionsGet200ResponseHiddenPlaceCountMin),
  id: zod.string(),
  places: zod.array(
    zod.strictObject({
      place: zod.strictObject({
        category: zod.strictObject({
          coverImageUrl: zod.string().nullable(),
          id: zod.string(),
          slug: zod.string(),
          title: zod.string(),
        }),
        coverImageUrl: zod.string().nullable(),
        id: zod.string(),
        slug: zod.string(),
        status: zod.enum(['active', 'hidden']),
        summary: zod.string(),
        tags: zod.array(zod.string()),
        title: zod.string(),
      }),
      position: zod.number().min(adminCollectionsGet200ResponsePlacesItemPositionMin),
    }),
  ),
  position: zod.number().min(adminCollectionsGet200ResponsePositionMin),
  slug: zod.string(),
  status: zod.enum(['draft', 'active']),
  title: zod.string(),
  updatedAt: zod.iso.datetime({ offset: true }),
});

/**
 * @summary Updated collection metadata.
 */
export const AdminCollectionsUpdateParams = zod.strictObject({
  collectionId: zod.string(),
});

export const adminCollectionsUpdateBodyDescriptionMax = 10000;

export const adminCollectionsUpdateBodySlugRegExp = new RegExp('^[a-z0-9]+(?:-[a-z0-9]+)\*$');

export const AdminCollectionsUpdateBody = zod.strictObject({
  description: zod.string().max(adminCollectionsUpdateBodyDescriptionMax).nullish(),
  slug: zod.string().min(1).regex(adminCollectionsUpdateBodySlugRegExp).optional(),
  title: zod.string().min(1).optional(),
});

export const adminCollectionsUpdate200ResponseActivePlaceCountMin = 0;

export const adminCollectionsUpdate200ResponseHiddenPlaceCountMin = 0;

export const adminCollectionsUpdate200ResponsePositionMin = 0;

export const AdminCollectionsUpdate200Response = zod.strictObject({
  activePlaceCount: zod.number().min(adminCollectionsUpdate200ResponseActivePlaceCountMin),
  coverImageUrl: zod.string().nullable(),
  createdAt: zod.iso.datetime({ offset: true }),
  description: zod.string().nullable(),
  hiddenPlaceCount: zod.number().min(adminCollectionsUpdate200ResponseHiddenPlaceCountMin),
  id: zod.string(),
  position: zod.number().min(adminCollectionsUpdate200ResponsePositionMin),
  slug: zod.string(),
  status: zod.enum(['draft', 'active']),
  title: zod.string(),
  updatedAt: zod.iso.datetime({ offset: true }),
});

/**
 * @summary Removed collection cover photo.
 */
export const AdminCollectionsRemovePhotoParams = zod.strictObject({
  collectionId: zod.string(),
});

/**
 * @summary Administrative collection cover image.
 */
export const AdminCollectionsGetPhotoParams = zod.strictObject({
  collectionId: zod.string(),
});

/**
 * @summary Collection with replaced cover photo.
 */
export const AdminCollectionsUploadPhotoParams = zod.strictObject({
  collectionId: zod.string(),
});

export const AdminCollectionsUploadPhotoBody = zod.strictObject({
  photo: zod.instanceof(File),
});

export const adminCollectionsUploadPhoto200ResponseActivePlaceCountMin = 0;

export const adminCollectionsUploadPhoto200ResponseHiddenPlaceCountMin = 0;

export const adminCollectionsUploadPhoto200ResponsePositionMin = 0;

export const AdminCollectionsUploadPhoto200Response = zod.strictObject({
  activePlaceCount: zod.number().min(adminCollectionsUploadPhoto200ResponseActivePlaceCountMin),
  coverImageUrl: zod.string().nullable(),
  createdAt: zod.iso.datetime({ offset: true }),
  description: zod.string().nullable(),
  hiddenPlaceCount: zod.number().min(adminCollectionsUploadPhoto200ResponseHiddenPlaceCountMin),
  id: zod.string(),
  position: zod.number().min(adminCollectionsUploadPhoto200ResponsePositionMin),
  slug: zod.string(),
  status: zod.enum(['draft', 'active']),
  title: zod.string(),
  updatedAt: zod.iso.datetime({ offset: true }),
});

/**
 * @summary Added place to collection.
 */
export const AdminCollectionsAddPlaceParams = zod.strictObject({
  collectionId: zod.string(),
});

export const AdminCollectionsAddPlaceBody = zod.strictObject({
  placeId: zod.string(),
});

/**
 * @summary Removed place from collection.
 */
export const AdminCollectionsRemovePlaceParams = zod.strictObject({
  placeId: zod.string(),
  collectionId: zod.string(),
});

/**
 * @summary Reordered places in a collection.
 */
export const AdminCollectionsReorderPlacesParams = zod.strictObject({
  collectionId: zod.string(),
});

export const AdminCollectionsReorderPlacesBody = zod.strictObject({
  placeIds: zod.array(zod.string()),
});

/**
 * @summary Updated collection lifecycle status.
 */
export const AdminCollectionsUpdateStatusParams = zod.strictObject({
  collectionId: zod.string(),
});

export const AdminCollectionsUpdateStatusBody = zod.strictObject({
  status: zod.enum(['draft', 'active']),
});

export const adminCollectionsUpdateStatus200ResponseActivePlaceCountMin = 0;

export const adminCollectionsUpdateStatus200ResponseHiddenPlaceCountMin = 0;

export const adminCollectionsUpdateStatus200ResponsePositionMin = 0;

export const AdminCollectionsUpdateStatus200Response = zod.strictObject({
  activePlaceCount: zod.number().min(adminCollectionsUpdateStatus200ResponseActivePlaceCountMin),
  coverImageUrl: zod.string().nullable(),
  createdAt: zod.iso.datetime({ offset: true }),
  description: zod.string().nullable(),
  hiddenPlaceCount: zod.number().min(adminCollectionsUpdateStatus200ResponseHiddenPlaceCountMin),
  id: zod.string(),
  position: zod.number().min(adminCollectionsUpdateStatus200ResponsePositionMin),
  slug: zod.string(),
  status: zod.enum(['draft', 'active']),
  title: zod.string(),
  updatedAt: zod.iso.datetime({ offset: true }),
});

/**
 * @summary Reordered collections.
 */
export const AdminCollectionsReorderBody = zod.strictObject({
  collectionIds: zod.array(zod.string()),
});
