/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * Amazing EKB backend contract.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * @summary Check process liveness
 */
export const HealthLive200Response = zod.strictObject({
  status: zod.enum(['ok']),
});

/**
 * @summary Check bounded dependency readiness
 */
export const HealthReady200Response = zod.strictObject({
  checks: zod
    .record(zod.string(), zod.enum(['up', 'down', 'skipped']))
    .describe('Extensible map of registered dependency names to their bounded check status.'),
  status: zod.enum(['ok', 'unavailable']),
});

export const HealthReady503Response = zod.strictObject({
  checks: zod
    .record(zod.string(), zod.enum(['up', 'down', 'skipped']))
    .describe('Extensible map of registered dependency names to their bounded check status.'),
  status: zod.enum(['ok', 'unavailable']),
});

/**
 * @summary Check the startup latch
 */
export const HealthStartup200Response = zod.strictObject({
  status: zod.enum(['ok', 'starting', 'unavailable']),
});

export const HealthStartup503Response = zod.strictObject({
  status: zod.enum(['ok', 'starting', 'unavailable']),
});
