/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * MVP backend API (OpenAPI-first)
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * Проверяет, что процесс приложения запущен и HTTP-слой отвечает на запросы.
 * @summary Liveness probe
 */
export const GetLiveness200Response = zod
  .strictObject({
    status: zod.string().describe('Признак живости приложения.'),
  })
  .describe('Ответ liveness-пробы. Показывает, что процесс приложения запущен.');

/**
 * Проверяет готовность приложения обслуживать запросы, включая доступность базы данных.
 * @summary Readiness probe
 */
export const GetReadiness200Response = zod
  .strictObject({
    status: zod.string().describe('Общий статус готовности.'),
    checks: zod
      .strictObject({
        database: zod.string().describe('Статус подключения к базе данных.'),
      })
      .describe('Результаты инфраструктурных проверок.'),
  })
  .describe('Ответ readiness-пробы. Показывает готовность приложения обслуживать запросы.');

export const GetReadiness503Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');
