/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * MVP backend API (OpenAPI-first)
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * Проверяет, что процесс приложения запущен и HTTP-слой отвечает на запросы.
 * @summary Liveness probe
 */
export const GetLiveness200Response = zod
  .strictObject({
    status: zod.string().describe('Признак живости приложения.'),
  })
  .describe('Ответ liveness-пробы. Показывает, что процесс приложения запущен.');

/**
 * Проверяет готовность приложения обслуживать запросы, включая доступность базы данных.
 * @summary Readiness probe
 */
export const GetReadiness200Response = zod
  .strictObject({
    status: zod.string().describe('Общий статус готовности.'),
    checks: zod
      .strictObject({
        database: zod.string().describe('Статус подключения к базе данных.'),
      })
      .describe('Результаты инфраструктурных проверок.'),
  })
  .describe('Ответ readiness-пробы. Показывает готовность приложения обслуживать запросы.');

export const GetReadiness503Response = zod
  .strictObject({
    meta: zod
      .strictObject({
        requestId: zod.string().describe('Идентификатор запроса для трассировки в логах.'),
      })
      .optional()
      .describe('Транспортные метаданные HTTP-ответа.'),
    error: zod
      .strictObject({
        type: zod
          .enum(['validation', 'domain', 'auth', 'permission', 'not_found', 'server'])
          .describe('Категория прикладной ошибки по стандарту `STD-001`.'),
        code: zod.string().describe('Машиночитаемый код ошибки.'),
        message: zod.string().describe('Человекочитаемое summary-сообщение.'),
        details: zod
          .strictObject({
            issues: zod
              .array(
                zod
                  .strictObject({
                    code: zod.string().describe('Машиночитаемый код проблемы.'),
                    message: zod.string().describe('Человекочитаемое описание проблемы.'),
                    path: zod.string().optional().describe('Путь к полю запроса в `dot notation`.'),
                  })
                  .describe('Одна конкретная проблема валидации или нарушения бизнес-правила.'),
              )
              .min(1)
              .optional()
              .describe('Список конкретных validation\/domain issues.'),
          })
          .optional()
          .describe('Дополнительные сведения для type-specific ошибок.'),
      })
      .describe('Канонический payload прикладной ошибки.'),
  })
  .describe('Единый HTTP error envelope по стандарту `STD-001`.');
