/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * Amazing EKB backend contract.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * @summary Administrative import run list.
 */
export const AdminImportRunsListQueryParams = zod.strictObject({
  sourceId: zod.string().optional(),
  status: zod.enum(['queued', 'running', 'completed', 'failed']).optional(),
});

export const adminImportRunsList200ResponseItemsItemCreatedCountMin = 0;

export const adminImportRunsList200ResponseItemsItemFoundCountMin = 0;

export const adminImportRunsList200ResponseItemsItemSkippedDuplicateCountMin = 0;

export const adminImportRunsList200ResponseItemsItemUpdatedCountMin = 0;

export const AdminImportRunsList200Response = zod.strictObject({
  items: zod.array(
    zod.strictObject({
      createdAt: zod.iso.datetime({ offset: true }),
      createdCount: zod.number().min(adminImportRunsList200ResponseItemsItemCreatedCountMin),
      errorMessage: zod.string().nullable(),
      finishedAt: zod.iso.datetime({ offset: true }).nullable(),
      foundCount: zod.number().min(adminImportRunsList200ResponseItemsItemFoundCountMin),
      id: zod.string(),
      skippedDuplicateCount: zod
        .number()
        .min(adminImportRunsList200ResponseItemsItemSkippedDuplicateCountMin),
      sourceId: zod.string(),
      startedAt: zod.iso.datetime({ offset: true }).nullable(),
      status: zod.enum(['queued', 'running', 'completed', 'failed']),
      updatedAt: zod.iso.datetime({ offset: true }),
      updatedCount: zod.number().min(adminImportRunsList200ResponseItemsItemUpdatedCountMin),
    }),
  ),
});

/**
 * @summary Import run server-sent events.
 */
export const AdminImportRunsStreamEventsParams = zod.strictObject({
  runId: zod.string(),
});
