/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * Amazing EKB backend contract.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * @summary Place import operation snapshot.
 */
export const AdminPlaceImportsGetParams = zod.strictObject({
  operationId: zod.string(),
});

export const adminPlaceImportsGet200ResponseAttemptMin = 0;

export const adminPlaceImportsGet200ResponseVersionMin = 0;

export const AdminPlaceImportsGet200Response = zod.strictObject({
  attempt: zod.number().min(adminPlaceImportsGet200ResponseAttemptMin),
  captchaExpiresAt: zod.iso.datetime({ offset: true }).nullable(),
  category: zod
    .strictObject({
      id: zod.string().nullable(),
      resolution: zod.enum(['existing', 'will_create', 'created']),
      status: zod.enum(['draft', 'active']).nullable(),
      title: zod.string(),
    })
    .nullable(),
  createdAt: zod.iso.datetime({ offset: true }),
  error: zod
    .strictObject({
      code: zod.enum([
        'invalid_url',
        'not_organization_url',
        'redirect_not_allowed',
        'source_not_found',
        'captcha_session_expired',
        'source_blocked',
        'source_timeout',
        'parse_failed',
        'missing_title',
        'missing_primary_category',
        'missing_organization_id',
        'category_conflict',
        'external_identity_conflict',
        'confirmation_expired',
        'internal_error',
      ]),
      message: zod.string(),
    })
    .nullable(),
  id: zod.string(),
  mapsUrl: zod.url().nullable(),
  organizationId: zod.string().nullable(),
  outcome: zod.enum(['created', 'already_exists']).nullable(),
  possibleDuplicate: zod
    .strictObject({
      placeId: zod.string(),
      title: zod.string(),
    })
    .nullable(),
  previewExpiresAt: zod.iso.datetime({ offset: true }).nullable(),
  resultPlaceId: zod.string().nullable(),
  sourceUrl: zod.url(),
  status: zod.enum([
    'queued',
    'parsing',
    'awaiting_captcha',
    'preview_ready',
    'completed',
    'failed',
    'expired',
    'cancelled',
  ]),
  targetCollection: zod
    .strictObject({
      id: zod.string().nullable(),
      slug: zod.string(),
      title: zod.string(),
    })
    .nullable(),
  title: zod.string().nullable(),
  updatedAt: zod.iso.datetime({ offset: true }),
  version: zod.number().min(adminPlaceImportsGet200ResponseVersionMin),
});

/**
 * @summary Cancelled place import operation.
 */
export const AdminPlaceImportsCancelParams = zod.strictObject({
  operationId: zod.string(),
});

export const adminPlaceImportsCancel201ResponseAttemptMin = 0;

export const adminPlaceImportsCancel201ResponseVersionMin = 0;

export const AdminPlaceImportsCancel201Response = zod.strictObject({
  attempt: zod.number().min(adminPlaceImportsCancel201ResponseAttemptMin),
  captchaExpiresAt: zod.iso.datetime({ offset: true }).nullable(),
  category: zod
    .strictObject({
      id: zod.string().nullable(),
      resolution: zod.enum(['existing', 'will_create', 'created']),
      status: zod.enum(['draft', 'active']).nullable(),
      title: zod.string(),
    })
    .nullable(),
  createdAt: zod.iso.datetime({ offset: true }),
  error: zod
    .strictObject({
      code: zod.enum([
        'invalid_url',
        'not_organization_url',
        'redirect_not_allowed',
        'source_not_found',
        'captcha_session_expired',
        'source_blocked',
        'source_timeout',
        'parse_failed',
        'missing_title',
        'missing_primary_category',
        'missing_organization_id',
        'category_conflict',
        'external_identity_conflict',
        'confirmation_expired',
        'internal_error',
      ]),
      message: zod.string(),
    })
    .nullable(),
  id: zod.string(),
  mapsUrl: zod.url().nullable(),
  organizationId: zod.string().nullable(),
  outcome: zod.enum(['created', 'already_exists']).nullable(),
  possibleDuplicate: zod
    .strictObject({
      placeId: zod.string(),
      title: zod.string(),
    })
    .nullable(),
  previewExpiresAt: zod.iso.datetime({ offset: true }).nullable(),
  resultPlaceId: zod.string().nullable(),
  sourceUrl: zod.url(),
  status: zod.enum([
    'queued',
    'parsing',
    'awaiting_captcha',
    'preview_ready',
    'completed',
    'failed',
    'expired',
    'cancelled',
  ]),
  targetCollection: zod
    .strictObject({
      id: zod.string().nullable(),
      slug: zod.string(),
      title: zod.string(),
    })
    .nullable(),
  title: zod.string().nullable(),
  updatedAt: zod.iso.datetime({ offset: true }),
  version: zod.number().min(adminPlaceImportsCancel201ResponseVersionMin),
});

/**
 * @summary Confirmed place import operation.
 */
export const AdminPlaceImportsConfirmParams = zod.strictObject({
  operationId: zod.string(),
});

export const adminPlaceImportsConfirm201ResponseAttemptMin = 0;

export const adminPlaceImportsConfirm201ResponseVersionMin = 0;

export const AdminPlaceImportsConfirm201Response = zod.strictObject({
  attempt: zod.number().min(adminPlaceImportsConfirm201ResponseAttemptMin),
  captchaExpiresAt: zod.iso.datetime({ offset: true }).nullable(),
  category: zod
    .strictObject({
      id: zod.string().nullable(),
      resolution: zod.enum(['existing', 'will_create', 'created']),
      status: zod.enum(['draft', 'active']).nullable(),
      title: zod.string(),
    })
    .nullable(),
  createdAt: zod.iso.datetime({ offset: true }),
  error: zod
    .strictObject({
      code: zod.enum([
        'invalid_url',
        'not_organization_url',
        'redirect_not_allowed',
        'source_not_found',
        'captcha_session_expired',
        'source_blocked',
        'source_timeout',
        'parse_failed',
        'missing_title',
        'missing_primary_category',
        'missing_organization_id',
        'category_conflict',
        'external_identity_conflict',
        'confirmation_expired',
        'internal_error',
      ]),
      message: zod.string(),
    })
    .nullable(),
  id: zod.string(),
  mapsUrl: zod.url().nullable(),
  organizationId: zod.string().nullable(),
  outcome: zod.enum(['created', 'already_exists']).nullable(),
  possibleDuplicate: zod
    .strictObject({
      placeId: zod.string(),
      title: zod.string(),
    })
    .nullable(),
  previewExpiresAt: zod.iso.datetime({ offset: true }).nullable(),
  resultPlaceId: zod.string().nullable(),
  sourceUrl: zod.url(),
  status: zod.enum([
    'queued',
    'parsing',
    'awaiting_captcha',
    'preview_ready',
    'completed',
    'failed',
    'expired',
    'cancelled',
  ]),
  targetCollection: zod
    .strictObject({
      id: zod.string().nullable(),
      slug: zod.string(),
      title: zod.string(),
    })
    .nullable(),
  title: zod.string().nullable(),
  updatedAt: zod.iso.datetime({ offset: true }),
  version: zod.number().min(adminPlaceImportsConfirm201ResponseVersionMin),
});

/**
 * @summary Place import event delta.
 */
export const AdminPlaceImportsGetEventsParams = zod.strictObject({
  operationId: zod.string(),
});

export const adminPlaceImportsGetEventsQueryAfterVersionDefault = 0;
export const adminPlaceImportsGetEventsQueryAfterVersionMin = 0;

export const AdminPlaceImportsGetEventsQueryParams = zod.strictObject({
  afterVersion: zod
    .number()
    .min(adminPlaceImportsGetEventsQueryAfterVersionMin)
    .default(adminPlaceImportsGetEventsQueryAfterVersionDefault),
});

export const adminPlaceImportsGetEvents200ResponseEventsItemVersionMin = 0;

export const adminPlaceImportsGetEvents200ResponseOperationAttemptMin = 0;

export const adminPlaceImportsGetEvents200ResponseOperationVersionMin = 0;

export const AdminPlaceImportsGetEvents200Response = zod.strictObject({
  events: zod.array(
    zod.strictObject({
      createdAt: zod.iso.datetime({ offset: true }),
      id: zod.string(),
      operationId: zod.string(),
      seq: zod.number().min(1),
      status: zod.enum([
        'queued',
        'parsing',
        'awaiting_captcha',
        'preview_ready',
        'completed',
        'failed',
        'expired',
        'cancelled',
      ]),
      type: zod.string(),
      version: zod.number().min(adminPlaceImportsGetEvents200ResponseEventsItemVersionMin),
    }),
  ),
  operation: zod.strictObject({
    attempt: zod.number().min(adminPlaceImportsGetEvents200ResponseOperationAttemptMin),
    captchaExpiresAt: zod.iso.datetime({ offset: true }).nullable(),
    category: zod
      .strictObject({
        id: zod.string().nullable(),
        resolution: zod.enum(['existing', 'will_create', 'created']),
        status: zod.enum(['draft', 'active']).nullable(),
        title: zod.string(),
      })
      .nullable(),
    createdAt: zod.iso.datetime({ offset: true }),
    error: zod
      .strictObject({
        code: zod.enum([
          'invalid_url',
          'not_organization_url',
          'redirect_not_allowed',
          'source_not_found',
          'captcha_session_expired',
          'source_blocked',
          'source_timeout',
          'parse_failed',
          'missing_title',
          'missing_primary_category',
          'missing_organization_id',
          'category_conflict',
          'external_identity_conflict',
          'confirmation_expired',
          'internal_error',
        ]),
        message: zod.string(),
      })
      .nullable(),
    id: zod.string(),
    mapsUrl: zod.url().nullable(),
    organizationId: zod.string().nullable(),
    outcome: zod.enum(['created', 'already_exists']).nullable(),
    possibleDuplicate: zod
      .strictObject({
        placeId: zod.string(),
        title: zod.string(),
      })
      .nullable(),
    previewExpiresAt: zod.iso.datetime({ offset: true }).nullable(),
    resultPlaceId: zod.string().nullable(),
    sourceUrl: zod.url(),
    status: zod.enum([
      'queued',
      'parsing',
      'awaiting_captcha',
      'preview_ready',
      'completed',
      'failed',
      'expired',
      'cancelled',
    ]),
    targetCollection: zod
      .strictObject({
        id: zod.string().nullable(),
        slug: zod.string(),
        title: zod.string(),
      })
      .nullable(),
    title: zod.string().nullable(),
    updatedAt: zod.iso.datetime({ offset: true }),
    version: zod.number().min(adminPlaceImportsGetEvents200ResponseOperationVersionMin),
  }),
});

/**
 * @summary Place import server-sent events.
 */
export const AdminPlaceImportsStreamEventsParams = zod.strictObject({
  operationId: zod.string(),
});

export const adminPlaceImportsStreamEventsQueryAfterVersionDefault = 0;
export const adminPlaceImportsStreamEventsQueryAfterVersionMin = 0;

export const AdminPlaceImportsStreamEventsQueryParams = zod.strictObject({
  afterVersion: zod
    .number()
    .min(adminPlaceImportsStreamEventsQueryAfterVersionMin)
    .default(adminPlaceImportsStreamEventsQueryAfterVersionDefault),
});

/**
 * @summary Revoked place import viewer capability.
 */
export const AdminPlaceImportsRevokeViewerAccessParams = zod.strictObject({
  operationId: zod.string(),
});

/**
 * @summary Place import viewer capability.
 */
export const AdminPlaceImportsCreateViewerAccessParams = zod.strictObject({
  operationId: zod.string(),
});

export const AdminPlaceImportsCreateViewerAccess201Response = zod.strictObject({
  expiresAt: zod.iso.datetime({ offset: true }),
  viewerUrl: zod.url(),
});

/**
 * @summary Active place import operation.
 */
export const adminPlaceImportsGetActive200ResponseAttemptMin = 0;

export const adminPlaceImportsGetActive200ResponseVersionMin = 0;

export const AdminPlaceImportsGetActive200Response = zod.strictObject({
  attempt: zod.number().min(adminPlaceImportsGetActive200ResponseAttemptMin),
  captchaExpiresAt: zod.iso.datetime({ offset: true }).nullable(),
  category: zod
    .strictObject({
      id: zod.string().nullable(),
      resolution: zod.enum(['existing', 'will_create', 'created']),
      status: zod.enum(['draft', 'active']).nullable(),
      title: zod.string(),
    })
    .nullable(),
  createdAt: zod.iso.datetime({ offset: true }),
  error: zod
    .strictObject({
      code: zod.enum([
        'invalid_url',
        'not_organization_url',
        'redirect_not_allowed',
        'source_not_found',
        'captcha_session_expired',
        'source_blocked',
        'source_timeout',
        'parse_failed',
        'missing_title',
        'missing_primary_category',
        'missing_organization_id',
        'category_conflict',
        'external_identity_conflict',
        'confirmation_expired',
        'internal_error',
      ]),
      message: zod.string(),
    })
    .nullable(),
  id: zod.string(),
  mapsUrl: zod.url().nullable(),
  organizationId: zod.string().nullable(),
  outcome: zod.enum(['created', 'already_exists']).nullable(),
  possibleDuplicate: zod
    .strictObject({
      placeId: zod.string(),
      title: zod.string(),
    })
    .nullable(),
  previewExpiresAt: zod.iso.datetime({ offset: true }).nullable(),
  resultPlaceId: zod.string().nullable(),
  sourceUrl: zod.url(),
  status: zod.enum([
    'queued',
    'parsing',
    'awaiting_captcha',
    'preview_ready',
    'completed',
    'failed',
    'expired',
    'cancelled',
  ]),
  targetCollection: zod
    .strictObject({
      id: zod.string().nullable(),
      slug: zod.string(),
      title: zod.string(),
    })
    .nullable(),
  title: zod.string().nullable(),
  updatedAt: zod.iso.datetime({ offset: true }),
  version: zod.number().min(adminPlaceImportsGetActive200ResponseVersionMin),
});

/**
 * @summary Accepted place import operation.
 */

export const adminPlaceImportsStartBodyUrlMax = 2048;

export const AdminPlaceImportsStartBody = zod.strictObject({
  targetCollectionId: zod.string().min(1).optional(),
  url: zod.string().min(1).max(adminPlaceImportsStartBodyUrlMax),
});

export const adminPlaceImportsStart202ResponseAttemptMin = 0;

export const adminPlaceImportsStart202ResponseVersionMin = 0;

export const AdminPlaceImportsStart202Response = zod.strictObject({
  attempt: zod.number().min(adminPlaceImportsStart202ResponseAttemptMin),
  captchaExpiresAt: zod.iso.datetime({ offset: true }).nullable(),
  category: zod
    .strictObject({
      id: zod.string().nullable(),
      resolution: zod.enum(['existing', 'will_create', 'created']),
      status: zod.enum(['draft', 'active']).nullable(),
      title: zod.string(),
    })
    .nullable(),
  createdAt: zod.iso.datetime({ offset: true }),
  error: zod
    .strictObject({
      code: zod.enum([
        'invalid_url',
        'not_organization_url',
        'redirect_not_allowed',
        'source_not_found',
        'captcha_session_expired',
        'source_blocked',
        'source_timeout',
        'parse_failed',
        'missing_title',
        'missing_primary_category',
        'missing_organization_id',
        'category_conflict',
        'external_identity_conflict',
        'confirmation_expired',
        'internal_error',
      ]),
      message: zod.string(),
    })
    .nullable(),
  id: zod.string(),
  mapsUrl: zod.url().nullable(),
  organizationId: zod.string().nullable(),
  outcome: zod.enum(['created', 'already_exists']).nullable(),
  possibleDuplicate: zod
    .strictObject({
      placeId: zod.string(),
      title: zod.string(),
    })
    .nullable(),
  previewExpiresAt: zod.iso.datetime({ offset: true }).nullable(),
  resultPlaceId: zod.string().nullable(),
  sourceUrl: zod.url(),
  status: zod.enum([
    'queued',
    'parsing',
    'awaiting_captcha',
    'preview_ready',
    'completed',
    'failed',
    'expired',
    'cancelled',
  ]),
  targetCollection: zod
    .strictObject({
      id: zod.string().nullable(),
      slug: zod.string(),
      title: zod.string(),
    })
    .nullable(),
  title: zod.string().nullable(),
  updatedAt: zod.iso.datetime({ offset: true }),
  version: zod.number().min(adminPlaceImportsStart202ResponseVersionMin),
});
