/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * Amazing EKB backend contract.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * @summary Public category list.
 */
export const CategoriesList200Response = zod.strictObject({
  items: zod.array(
    zod.strictObject({
      coverImageUrl: zod.string().nullable(),
      id: zod.string(),
      slug: zod.string(),
      title: zod.string(),
    }),
  ),
});

/**
 * @summary Public category.
 */
export const CategoriesGetParams = zod.strictObject({
  categorySlug: zod.string(),
});

export const CategoriesGet200Response = zod.strictObject({
  coverImageUrl: zod.string().nullable(),
  id: zod.string(),
  slug: zod.string(),
  title: zod.string(),
});

/**
 * @summary Category cover image.
 */
export const CategoriesGetPhotoParams = zod.strictObject({
  categorySlug: zod.string(),
});
