/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * Amazing EKB backend contract.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * @summary Administrative place list.
 */
export const adminPlacesListQueryPageDefault = 1;

export const adminPlacesListQueryPageSizeDefault = 20;
export const adminPlacesListQueryPageSizeMax = 100;

export const AdminPlacesListQueryParams = zod.strictObject({
  page: zod.number().min(1).default(adminPlacesListQueryPageDefault),
  pageSize: zod
    .number()
    .min(1)
    .max(adminPlacesListQueryPageSizeMax)
    .default(adminPlacesListQueryPageSizeDefault),
  status: zod.enum(['active', 'hidden']).optional(),
});

export const adminPlacesList200ResponseTotalMin = 0;

export const AdminPlacesList200Response = zod.strictObject({
  items: zod.array(
    zod.strictObject({
      category: zod.strictObject({
        coverImageUrl: zod.string().nullable(),
        id: zod.string(),
        slug: zod.string(),
        title: zod.string(),
      }),
      coverImageUrl: zod.string().nullable(),
      id: zod.string(),
      mapsUrl: zod.url().nullable(),
      slug: zod.string(),
      status: zod.enum(['active', 'hidden']),
      summary: zod.string(),
      tags: zod.array(zod.string()),
      title: zod.string(),
    }),
  ),
  page: zod.number().min(1),
  pageSize: zod.number().min(1),
  total: zod.number().min(adminPlacesList200ResponseTotalMin),
});

/**
 * @summary Created place.
 */

export const adminPlacesCreateBodySlugRegExp = new RegExp('^[a-z0-9]+(?:-[a-z0-9]+)\*$');

export const AdminPlacesCreateBody = zod.strictObject({
  categoryId: zod.string().min(1),
  slug: zod.string().min(1).regex(adminPlacesCreateBodySlugRegExp).nullish(),
  summary: zod.string().optional(),
  tags: zod.array(zod.string()).optional(),
  title: zod.string(),
});

export const AdminPlacesCreate201Response = zod.strictObject({
  category: zod.strictObject({
    coverImageUrl: zod.string().nullable(),
    id: zod.string(),
    slug: zod.string(),
    title: zod.string(),
  }),
  coverImageUrl: zod.string().nullable(),
  id: zod.string(),
  slug: zod.string(),
  status: zod.enum(['active', 'hidden']),
  summary: zod.string(),
  tags: zod.array(zod.string()),
  title: zod.string(),
});

/**
 * @summary Administrative place detail.
 */
export const AdminPlacesGetParams = zod.strictObject({
  placeId: zod.string(),
});

export const adminPlacesGet200ResponseCountersDzenMin = 0;

export const adminPlacesGet200ResponseCountersInstagramMin = 0;

export const adminPlacesGet200ResponseCountersTelegramMin = 0;

export const adminPlacesGet200ResponsePinnedMaterialOneDurationSecMin = 0;

export const AdminPlacesGet200Response = zod.strictObject({
  category: zod.strictObject({
    coverImageUrl: zod.string().nullable(),
    id: zod.string(),
    slug: zod.string(),
    title: zod.string(),
  }),
  counters: zod.strictObject({
    dzen: zod.number().min(adminPlacesGet200ResponseCountersDzenMin),
    instagram: zod.number().min(adminPlacesGet200ResponseCountersInstagramMin),
    telegram: zod.number().min(adminPlacesGet200ResponseCountersTelegramMin),
  }),
  coverImageUrl: zod.string().nullable(),
  id: zod.string(),
  mapsUrl: zod.url().nullable(),
  pinnedMaterial: zod
    .strictObject({
      durationSec: zod
        .number()
        .min(adminPlacesGet200ResponsePinnedMaterialOneDurationSecMin)
        .nullable(),
      id: zod.string(),
      placeId: zod.string(),
      platform: zod.enum(['dzen', 'telegram', 'instagram']),
      publishedAt: zod.iso.date(),
      redirectUrl: zod.string().nullable(),
      title: zod.string().nullable(),
      type: zod.enum(['post', 'reel', 'video']),
    })
    .nullable(),
  slug: zod.string(),
  status: zod.enum(['active', 'hidden']),
  summary: zod.string(),
  tags: zod.array(zod.string()),
  title: zod.string(),
});

/**
 * @summary Updated place.
 */
export const AdminPlacesUpdateParams = zod.strictObject({
  placeId: zod.string(),
});

export const adminPlacesUpdateBodySlugRegExp = new RegExp('^[a-z0-9]+(?:-[a-z0-9]+)\*$');

export const AdminPlacesUpdateBody = zod.strictObject({
  categoryId: zod.string().min(1).nullish(),
  slug: zod.string().min(1).regex(adminPlacesUpdateBodySlugRegExp).optional(),
  summary: zod.string().nullish(),
  tags: zod.array(zod.string()).nullish(),
  title: zod.string().nullish(),
});

export const AdminPlacesUpdate200Response = zod.strictObject({
  category: zod.strictObject({
    coverImageUrl: zod.string().nullable(),
    id: zod.string(),
    slug: zod.string(),
    title: zod.string(),
  }),
  coverImageUrl: zod.string().nullable(),
  id: zod.string(),
  slug: zod.string(),
  status: zod.enum(['active', 'hidden']),
  summary: zod.string(),
  tags: zod.array(zod.string()),
  title: zod.string(),
});

/**
 * @summary Administrative place material list.
 */
export const AdminPlaceMaterialsListParams = zod.strictObject({
  placeId: zod.string(),
});

export const AdminPlaceMaterialsListQueryParams = zod.strictObject({
  platform: zod.enum(['dzen', 'telegram', 'instagram']).optional(),
});

export const adminPlaceMaterialsList200ResponseItemsItemDurationSecMin = 0;

export const AdminPlaceMaterialsList200Response = zod.strictObject({
  items: zod.array(
    zod.strictObject({
      durationSec: zod
        .number()
        .min(adminPlaceMaterialsList200ResponseItemsItemDurationSecMin)
        .nullable(),
      id: zod.string(),
      placeId: zod.string(),
      platform: zod.enum(['dzen', 'telegram', 'instagram']),
      publishedAt: zod.iso.date(),
      redirectUrl: zod.string().nullable(),
      title: zod.string().nullable(),
      type: zod.enum(['post', 'reel', 'video']),
      url: zod.url(),
    }),
  ),
});

/**
 * @summary Created place material.
 */
export const AdminPlaceMaterialsCreateParams = zod.strictObject({
  placeId: zod.string(),
});

export const adminPlaceMaterialsCreateBodyDurationSecMin = 0;

export const AdminPlaceMaterialsCreateBody = zod.strictObject({
  durationSec: zod.number().min(adminPlaceMaterialsCreateBodyDurationSecMin).nullish(),
  platform: zod.enum(['dzen', 'telegram', 'instagram']),
  publishedAt: zod.iso.date(),
  title: zod.string(),
  type: zod.enum(['post', 'reel', 'video']),
  url: zod.url(),
});

export const adminPlaceMaterialsCreate201ResponseDurationSecMin = 0;

export const AdminPlaceMaterialsCreate201Response = zod.strictObject({
  durationSec: zod.number().min(adminPlaceMaterialsCreate201ResponseDurationSecMin).nullable(),
  id: zod.string(),
  placeId: zod.string(),
  platform: zod.enum(['dzen', 'telegram', 'instagram']),
  publishedAt: zod.iso.date(),
  redirectUrl: zod.string().nullable(),
  title: zod.string().nullable(),
  type: zod.enum(['post', 'reel', 'video']),
  url: zod.url(),
});

/**
 * @summary Hidden place material link.
 */
export const AdminPlaceMaterialsHideParams = zod.strictObject({
  materialId: zod.string(),
  placeId: zod.string(),
});

/**
 * @summary Updated place material link.
 */
export const AdminPlaceMaterialsUpdateLinkParams = zod.strictObject({
  materialId: zod.string(),
  placeId: zod.string(),
});

export const adminPlaceMaterialsUpdateLinkBodySortOrderMin = 0;

export const AdminPlaceMaterialsUpdateLinkBody = zod.strictObject({
  isPinned: zod.boolean().optional(),
  sortOrder: zod.number().min(adminPlaceMaterialsUpdateLinkBodySortOrderMin).optional(),
});

export const adminPlaceMaterialsUpdateLink200ResponseDurationSecMin = 0;

export const AdminPlaceMaterialsUpdateLink200Response = zod.strictObject({
  durationSec: zod.number().min(adminPlaceMaterialsUpdateLink200ResponseDurationSecMin).nullable(),
  id: zod.string(),
  placeId: zod.string(),
  platform: zod.enum(['dzen', 'telegram', 'instagram']),
  publishedAt: zod.iso.date(),
  redirectUrl: zod.string().nullable(),
  title: zod.string().nullable(),
  type: zod.enum(['post', 'reel', 'video']),
  url: zod.url(),
});

/**
 * @summary Linked place material.
 */
export const AdminPlaceMaterialsLinkParams = zod.strictObject({
  materialId: zod.string(),
  placeId: zod.string(),
});

export const adminPlaceMaterialsLink200ResponseDurationSecMin = 0;

export const AdminPlaceMaterialsLink200Response = zod.strictObject({
  durationSec: zod.number().min(adminPlaceMaterialsLink200ResponseDurationSecMin).nullable(),
  id: zod.string(),
  placeId: zod.string(),
  platform: zod.enum(['dzen', 'telegram', 'instagram']),
  publishedAt: zod.iso.date(),
  redirectUrl: zod.string().nullable(),
  title: zod.string().nullable(),
  type: zod.enum(['post', 'reel', 'video']),
  url: zod.url(),
});

/**
 * @summary Place with replaced cover photo.
 */
export const AdminPlacesUploadPhotoParams = zod.strictObject({
  placeId: zod.string(),
});

export const AdminPlacesUploadPhotoBody = zod.strictObject({
  photo: zod.instanceof(File),
});

export const AdminPlacesUploadPhoto200Response = zod.strictObject({
  category: zod.strictObject({
    coverImageUrl: zod.string().nullable(),
    id: zod.string(),
    slug: zod.string(),
    title: zod.string(),
  }),
  coverImageUrl: zod.string().nullable(),
  id: zod.string(),
  slug: zod.string(),
  status: zod.enum(['active', 'hidden']),
  summary: zod.string(),
  tags: zod.array(zod.string()),
  title: zod.string(),
});

/**
 * @summary Place without pinned material.
 */
export const AdminPlacesClearPinnedMaterialParams = zod.strictObject({
  placeId: zod.string(),
});

export const adminPlacesClearPinnedMaterial200ResponseCountersDzenMin = 0;

export const adminPlacesClearPinnedMaterial200ResponseCountersInstagramMin = 0;

export const adminPlacesClearPinnedMaterial200ResponseCountersTelegramMin = 0;

export const adminPlacesClearPinnedMaterial200ResponsePinnedMaterialOneDurationSecMin = 0;

export const AdminPlacesClearPinnedMaterial200Response = zod.strictObject({
  category: zod.strictObject({
    coverImageUrl: zod.string().nullable(),
    id: zod.string(),
    slug: zod.string(),
    title: zod.string(),
  }),
  counters: zod.strictObject({
    dzen: zod.number().min(adminPlacesClearPinnedMaterial200ResponseCountersDzenMin),
    instagram: zod.number().min(adminPlacesClearPinnedMaterial200ResponseCountersInstagramMin),
    telegram: zod.number().min(adminPlacesClearPinnedMaterial200ResponseCountersTelegramMin),
  }),
  coverImageUrl: zod.string().nullable(),
  id: zod.string(),
  mapsUrl: zod.url().nullable(),
  pinnedMaterial: zod
    .strictObject({
      durationSec: zod
        .number()
        .min(adminPlacesClearPinnedMaterial200ResponsePinnedMaterialOneDurationSecMin)
        .nullable(),
      id: zod.string(),
      placeId: zod.string(),
      platform: zod.enum(['dzen', 'telegram', 'instagram']),
      publishedAt: zod.iso.date(),
      redirectUrl: zod.string().nullable(),
      title: zod.string().nullable(),
      type: zod.enum(['post', 'reel', 'video']),
    })
    .nullable(),
  slug: zod.string(),
  status: zod.enum(['active', 'hidden']),
  summary: zod.string(),
  tags: zod.array(zod.string()),
  title: zod.string(),
});

/**
 * @summary Place with pinned material.
 */
export const AdminPlacesSetPinnedMaterialParams = zod.strictObject({
  placeId: zod.string(),
});

export const AdminPlacesSetPinnedMaterialBody = zod.strictObject({
  materialId: zod.string(),
});

export const adminPlacesSetPinnedMaterial200ResponseCountersDzenMin = 0;

export const adminPlacesSetPinnedMaterial200ResponseCountersInstagramMin = 0;

export const adminPlacesSetPinnedMaterial200ResponseCountersTelegramMin = 0;

export const adminPlacesSetPinnedMaterial200ResponsePinnedMaterialOneDurationSecMin = 0;

export const AdminPlacesSetPinnedMaterial200Response = zod.strictObject({
  category: zod.strictObject({
    coverImageUrl: zod.string().nullable(),
    id: zod.string(),
    slug: zod.string(),
    title: zod.string(),
  }),
  counters: zod.strictObject({
    dzen: zod.number().min(adminPlacesSetPinnedMaterial200ResponseCountersDzenMin),
    instagram: zod.number().min(adminPlacesSetPinnedMaterial200ResponseCountersInstagramMin),
    telegram: zod.number().min(adminPlacesSetPinnedMaterial200ResponseCountersTelegramMin),
  }),
  coverImageUrl: zod.string().nullable(),
  id: zod.string(),
  mapsUrl: zod.url().nullable(),
  pinnedMaterial: zod
    .strictObject({
      durationSec: zod
        .number()
        .min(adminPlacesSetPinnedMaterial200ResponsePinnedMaterialOneDurationSecMin)
        .nullable(),
      id: zod.string(),
      placeId: zod.string(),
      platform: zod.enum(['dzen', 'telegram', 'instagram']),
      publishedAt: zod.iso.date(),
      redirectUrl: zod.string().nullable(),
      title: zod.string().nullable(),
      type: zod.enum(['post', 'reel', 'video']),
    })
    .nullable(),
  slug: zod.string(),
  status: zod.enum(['active', 'hidden']),
  summary: zod.string(),
  tags: zod.array(zod.string()),
  title: zod.string(),
});

/**
 * @summary Place with updated publication status.
 */
export const AdminPlacesUpdateStatusParams = zod.strictObject({
  placeId: zod.string(),
});

export const AdminPlacesUpdateStatusBody = zod.strictObject({
  status: zod.enum(['active', 'hidden']),
});

export const AdminPlacesUpdateStatus200Response = zod.strictObject({
  category: zod.strictObject({
    coverImageUrl: zod.string().nullable(),
    id: zod.string(),
    slug: zod.string(),
    title: zod.string(),
  }),
  coverImageUrl: zod.string().nullable(),
  id: zod.string(),
  slug: zod.string(),
  status: zod.enum(['active', 'hidden']),
  summary: zod.string(),
  tags: zod.array(zod.string()),
  title: zod.string(),
});
