/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * Amazing EKB backend contract.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * @summary Administrative material library.
 */

export const adminMaterialsListQueryPageDefault = 1;
export const adminMaterialsListQueryPageMax = 1000;

export const adminMaterialsListQueryPageSizeDefault = 100;
export const adminMaterialsListQueryPageSizeMax = 100;

export const AdminMaterialsListQueryParams = zod.strictObject({
  platform: zod.enum(['dzen', 'telegram', 'instagram']).optional(),
  placeId: zod.string().min(1).optional(),
  adminStatus: zod.enum(['pending', 'approved', 'rejected', 'archived']).optional(),
  linked: zod.boolean().optional(),
  page: zod
    .number()
    .min(1)
    .max(adminMaterialsListQueryPageMax)
    .default(adminMaterialsListQueryPageDefault),
  pageSize: zod
    .number()
    .min(1)
    .max(adminMaterialsListQueryPageSizeMax)
    .default(adminMaterialsListQueryPageSizeDefault),
});

export const adminMaterialsList200ResponseItemsItemDurationSecMin = 0;

export const adminMaterialsList200ResponseTotalMin = 0;

export const AdminMaterialsList200Response = zod.strictObject({
  items: zod.array(
    zod.strictObject({
      adminStatus: zod.enum(['pending', 'approved', 'rejected', 'archived']),
      durationSec: zod
        .number()
        .min(adminMaterialsList200ResponseItemsItemDurationSecMin)
        .nullable(),
      excerpt: zod.string().nullable(),
      externalId: zod.string().nullable(),
      id: zod.string(),
      linked: zod.boolean(),
      mediaKind: zod.string().nullable(),
      mediaPreviewUrl: zod.url().nullable(),
      placeLink: zod.enum(['active', 'hidden']).nullable(),
      platform: zod.enum(['dzen', 'telegram', 'instagram']),
      publishedAt: zod.iso.date(),
      source: zod
        .strictObject({
          displayName: zod.string(),
          id: zod.string(),
          platform: zod.string(),
          url: zod.url(),
        })
        .nullable(),
      text: zod.string().nullable(),
      title: zod.string().nullable(),
      type: zod.enum(['post', 'reel', 'video']),
      url: zod.url(),
    }),
  ),
  page: zod.number().min(1),
  pageSize: zod.number().min(1),
  total: zod.number().min(adminMaterialsList200ResponseTotalMin),
});

/**
 * @summary Updated material.
 */
export const AdminMaterialsUpdateParams = zod.strictObject({
  materialId: zod.string(),
});

export const adminMaterialsUpdateBodyDurationSecMin = 0;

export const AdminMaterialsUpdateBody = zod.strictObject({
  durationSec: zod.number().min(adminMaterialsUpdateBodyDurationSecMin).nullish(),
  platform: zod.enum(['dzen', 'telegram', 'instagram']).nullish(),
  publishedAt: zod.iso.date().optional(),
  title: zod.string().nullish(),
  type: zod.enum(['post', 'reel', 'video']).nullish(),
  url: zod.url().nullish(),
});

export const adminMaterialsUpdate200ResponseDurationSecMin = 0;

export const AdminMaterialsUpdate200Response = zod.strictObject({
  durationSec: zod.number().min(adminMaterialsUpdate200ResponseDurationSecMin).nullable(),
  id: zod.string(),
  placeId: zod.string(),
  platform: zod.enum(['dzen', 'telegram', 'instagram']),
  publishedAt: zod.iso.date(),
  redirectUrl: zod.string().nullable(),
  title: zod.string().nullable(),
  type: zod.enum(['post', 'reel', 'video']),
  url: zod.url(),
});

/**
 * @summary Material with updated review status.
 */
export const AdminMaterialsUpdateStatusParams = zod.strictObject({
  materialId: zod.string(),
});

export const AdminMaterialsUpdateStatusBody = zod.strictObject({
  adminStatus: zod.enum(['pending', 'approved', 'rejected', 'archived']),
});

export const adminMaterialsUpdateStatus200ResponseDurationSecMin = 0;

export const AdminMaterialsUpdateStatus200Response = zod.strictObject({
  adminStatus: zod.enum(['pending', 'approved', 'rejected', 'archived']),
  durationSec: zod.number().min(adminMaterialsUpdateStatus200ResponseDurationSecMin).nullable(),
  excerpt: zod.string().nullable(),
  externalId: zod.string().nullable(),
  id: zod.string(),
  linked: zod.boolean(),
  mediaKind: zod.string().nullable(),
  mediaPreviewUrl: zod.url().nullable(),
  placeLink: zod.enum(['active', 'hidden']).nullable(),
  platform: zod.enum(['dzen', 'telegram', 'instagram']),
  publishedAt: zod.iso.date(),
  source: zod
    .strictObject({
      displayName: zod.string(),
      id: zod.string(),
      platform: zod.string(),
      url: zod.url(),
    })
    .nullable(),
  text: zod.string().nullable(),
  title: zod.string().nullable(),
  type: zod.enum(['post', 'reel', 'video']),
  url: zod.url(),
});
