/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * Amazing EKB backend contract.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * @summary Temporary redirect to an allowlisted material URL.
 */
export const MaterialsRedirectParams = zod.strictObject({
  materialId: zod.string(),
});
