/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * MVP backend API (OpenAPI-first)
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * Возвращает публичный список мест с пагинацией, поиском и фильтрацией по категории.
 * @summary List places
 */
export const listPlacesQueryPageDefault = 1;

export const listPlacesQueryPageSizeDefault = 20;
export const listPlacesQueryPageSizeMax = 100;

export const listPlacesQuerySortDefault = `popular`;

export const ListPlacesQueryParams = zod.strictObject({
  page: zod
    .number()
    .min(1)
    .default(listPlacesQueryPageDefault)
    .describe('Номер страницы пагинации. Минимальное значение `1`.'),
  pageSize: zod
    .number()
    .min(1)
    .max(listPlacesQueryPageSizeMax)
    .default(listPlacesQueryPageSizeDefault)
    .describe('Размер страницы. Допустимый диапазон от `1` до `100`.'),
  search: zod.string().optional().describe('Полнотекстовый поиск по названию и описанию места.'),
  sort: zod
    .enum(['popular'])
    .default(listPlacesQuerySortDefault)
    .describe('Режим сортировки списка мест.'),
  category: zod
    .enum(['pools', 'spa', 'cafe', 'hotels', 'workshops'])
    .optional()
    .describe('Фильтр по категории места.'),
});

export const ListPlaces200Response = zod
  .strictObject({
    items: zod
      .array(
        zod
          .strictObject({
            id: zod.string().describe('Идентификатор места.'),
            title: zod.string().describe('Название места.'),
            summary: zod.string().describe('Короткое описание для каталога.'),
            tags: zod.array(zod.string()).describe('Набор тегов для поиска и фильтрации.'),
            category: zod
              .enum(['pools', 'spa', 'cafe', 'hotels', 'workshops'])
              .describe('Категория места в каталоге.'),
            status: zod.enum(['active', 'hidden']).describe('Статус публикации места.'),
            popularityWeight: zod.number().describe('Вес популярности для сортировки.'),
            coverImageUrl: zod
              .string()
              .nullable()
              .describe(
                'Публичный cover-фото места. Если фото отсутствует или не должно отдаться публично, возвращается `null`.',
              ),
          })
          .describe('Краткая карточка места, используемая в списках.'),
      )
      .describe('Элементы текущей страницы.'),
    total: zod.number().describe('Общее количество доступных элементов.'),
    page: zod.number().describe('Текущая страница.'),
    pageSize: zod.number().describe('Размер страницы.'),
  })
  .describe('Пагинированный список мест.');

export const ListPlaces400Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

/**
 * Возвращает детальную карточку публичного места по его идентификатору.
 * @summary Get place details
 */
export const GetPlaceDetailParams = zod.strictObject({
  placeId: zod.string().describe('Идентификатор места.'),
});

export const GetPlaceDetail200Response = zod
  .strictObject({
    id: zod.string().describe('Идентификатор места.'),
    title: zod.string().describe('Название места.'),
    summary: zod.string().describe('Короткое описание для каталога.'),
    tags: zod.array(zod.string()).describe('Набор тегов для поиска и фильтрации.'),
    category: zod
      .enum(['pools', 'spa', 'cafe', 'hotels', 'workshops'])
      .describe('Категория места в каталоге.'),
    status: zod.enum(['active', 'hidden']).describe('Статус публикации места.'),
    popularityWeight: zod.number().describe('Вес популярности для сортировки.'),
    coverImageUrl: zod
      .string()
      .nullable()
      .describe(
        'Публичный cover-фото места. Если фото отсутствует или не должно отдаться публично, возвращается `null`.',
      ),
    pinnedMaterial: zod
      .strictObject({
        id: zod.string().describe('Идентификатор материала.'),
        placeId: zod.string().describe('Идентификатор места, к которому относится материал.'),
        platform: zod
          .enum(['dzen', 'telegram', 'instagram'])
          .describe('Платформа, на которой опубликован материал.'),
        type: zod.enum(['post', 'reel', 'video']).describe('Тип материала.'),
        title: zod.string().describe('Заголовок материала.'),
        publishedAt: zod.iso
          .datetime({ offset: true })
          .describe('Дата и время публикации материала.'),
        durationSec: zod.number().nullable().describe('Длительность в секундах для видеоформатов.'),
        url: zod.url().describe('Публичная ссылка на материал.'),
      })
      .describe('Материал, связанный с местом.')
      .nullable()
      .describe('Закреплённый материал места, если он назначен.'),
    counters: zod
      .strictObject({
        dzen: zod.number(),
        telegram: zod.number(),
        instagram: zod.number(),
      })
      .describe('Количество материалов по платформам.'),
  })
  .describe('Детальная карточка места с pinned material и счетчиками по платформам.');

export const GetPlaceDetail404Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

/**
 * Возвращает бинарное содержимое публичного cover-фото активного места.
 * @summary Get place cover photo
 */
export const GetPlaceCoverPhotoParams = zod.strictObject({
  placeId: zod.string().describe('Идентификатор места.'),
});

export const GetPlaceCoverPhoto404Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

/**
 * Возвращает до 100 материалов, связанных с указанным активным местом, с опциональным фильтром по платформе.
 * @summary List place materials
 */
export const ListPlaceMaterialsParams = zod.strictObject({
  placeId: zod.string().describe('Идентификатор места.'),
});

export const ListPlaceMaterialsQueryParams = zod.strictObject({
  platform: zod
    .enum(['dzen', 'telegram', 'instagram'])
    .optional()
    .describe('Фильтр по платформе публикации материала.'),
});

export const ListPlaceMaterials200Response = zod
  .strictObject({
    items: zod
      .array(
        zod
          .strictObject({
            id: zod.string().describe('Идентификатор материала.'),
            placeId: zod.string().describe('Идентификатор места, к которому относится материал.'),
            platform: zod
              .enum(['dzen', 'telegram', 'instagram'])
              .describe('Платформа, на которой опубликован материал.'),
            type: zod.enum(['post', 'reel', 'video']).describe('Тип материала.'),
            title: zod.string().describe('Заголовок материала.'),
            publishedAt: zod.iso
              .datetime({ offset: true })
              .describe('Дата и время публикации материала.'),
            durationSec: zod
              .number()
              .nullable()
              .describe('Длительность в секундах для видеоформатов.'),
            url: zod.url().describe('Публичная ссылка на материал.'),
          })
          .describe('Материал, связанный с местом.'),
      )
      .describe('Материалы места в стабильном порядке отображения.'),
  })
  .describe('Ограниченный список материалов места.');

export const ListPlaceMaterials400Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const ListPlaceMaterials404Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');
