/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * MVP backend API (OpenAPI-first)
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * Возвращает публичный справочник категорий мест для фильтров и бейджей.
 * @summary List place categories
 */
export const ListPlaceCategories200Response = zod
  .strictObject({
    items: zod.array(
      zod
        .strictObject({
          id: zod.string().describe('Идентификатор категории.'),
          slug: zod.string().describe('Человекочитаемый slug категории.'),
          title: zod.string().describe('Название категории для интерфейса.'),
        })
        .describe('Публичная категория места для фильтров.'),
    ),
  })
  .describe('Публичный список категорий мест.');

/**
 * Возвращает публичную категорию места по её slug.
 * @summary Get place category
 */
export const getPlaceCategoryPathCategorySlugRegExp = new RegExp('^[a-z0-9]+(?:-[a-z0-9]+)\*$');

export const GetPlaceCategoryParams = zod.strictObject({
  categorySlug: zod
    .string()
    .regex(getPlaceCategoryPathCategorySlugRegExp)
    .describe('Публичный slug категории места.'),
});

export const GetPlaceCategory200Response = zod
  .strictObject({
    id: zod.string().describe('Идентификатор категории.'),
    slug: zod.string().describe('Человекочитаемый slug категории.'),
    title: zod.string().describe('Название категории для интерфейса.'),
  })
  .describe('Публичная категория места для фильтров.');

export const GetPlaceCategory404Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

/**
 * Возвращает публичный список мест с пагинацией, поиском и фильтрацией по категории в стабильном порядке `title ASC, id ASC`.
 * @summary List places
 */
export const listPlacesQueryPageDefault = 1;
export const listPlacesQueryPageMax = 1000;

export const listPlacesQueryPageSizeDefault = 20;
export const listPlacesQueryPageSizeMax = 100;

export const listPlacesQuerySearchMax = 100;

export const ListPlacesQueryParams = zod.strictObject({
  page: zod
    .number()
    .min(1)
    .max(listPlacesQueryPageMax)
    .default(listPlacesQueryPageDefault)
    .describe('Номер страницы пагинации. Допустимый диапазон от `1` до `1000`.'),
  pageSize: zod
    .number()
    .min(1)
    .max(listPlacesQueryPageSizeMax)
    .default(listPlacesQueryPageSizeDefault)
    .describe('Размер страницы. Допустимый диапазон от `1` до `100`.'),
  search: zod
    .string()
    .max(listPlacesQuerySearchMax)
    .optional()
    .describe('Полнотекстовый поиск по названию и описанию места. Максимум 100 символов.'),
  categoryId: zod.string().optional().describe('Фильтр по идентификатору категории места.'),
});

export const ListPlaces200Response = zod
  .strictObject({
    items: zod
      .array(
        zod
          .strictObject({
            id: zod.string().describe('Идентификатор места.'),
            slug: zod.string().describe('Публичный slug места.'),
            title: zod.string().describe('Название места.'),
            summary: zod.string().describe('Короткое описание для каталога.'),
            tags: zod.array(zod.string()).describe('Набор тегов для поиска и фильтрации.'),
            category: zod
              .strictObject({
                id: zod.string().describe('Идентификатор категории.'),
                slug: zod.string().describe('Человекочитаемый slug категории.'),
                title: zod.string().describe('Название категории для интерфейса.'),
              })
              .describe('Публичная категория места для фильтров.'),
            status: zod.enum(['active', 'hidden']).describe('Статус публикации места.'),
            coverImageUrl: zod
              .string()
              .nullable()
              .describe(
                'Публичный cover-фото места. Если фото отсутствует или не должно отдаться публично, возвращается `null`.',
              ),
            counters: zod
              .strictObject({
                dzen: zod.number(),
                telegram: zod.number(),
                instagram: zod.number(),
              })
              .describe('Количество материалов по платформам.'),
          })
          .describe('Краткая публичная карточка места со счетчиками материалов по платформам.'),
      )
      .describe('Элементы текущей страницы.'),
    total: zod.number().describe('Общее количество доступных элементов.'),
    page: zod.number().describe('Текущая страница.'),
    pageSize: zod.number().describe('Размер страницы.'),
  })
  .describe('Публичный пагинированный список мест со счетчиками материалов.');

export const ListPlaces400Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

/**
 * Возвращает детальную карточку публичного места по его slug.
 * @summary Get place details
 */
export const getPlaceDetailPathPlaceSlugRegExp = new RegExp('^[a-z0-9]+(?:-[a-z0-9]+)\*$');

export const GetPlaceDetailParams = zod.strictObject({
  placeSlug: zod
    .string()
    .regex(getPlaceDetailPathPlaceSlugRegExp)
    .describe('Публичный slug места.'),
});

export const GetPlaceDetail200Response = zod
  .strictObject({
    id: zod.string().describe('Идентификатор места.'),
    slug: zod.string().describe('Публичный slug места.'),
    title: zod.string().describe('Название места.'),
    summary: zod.string().describe('Короткое описание для каталога.'),
    tags: zod.array(zod.string()).describe('Набор тегов для поиска и фильтрации.'),
    category: zod
      .strictObject({
        id: zod.string().describe('Идентификатор категории.'),
        slug: zod.string().describe('Человекочитаемый slug категории.'),
        title: zod.string().describe('Название категории для интерфейса.'),
      })
      .describe('Публичная категория места для фильтров.'),
    status: zod.enum(['active', 'hidden']).describe('Статус публикации места.'),
    coverImageUrl: zod
      .string()
      .nullable()
      .describe(
        'Публичный cover-фото места. Если фото отсутствует или не должно отдаться публично, возвращается `null`.',
      ),
    counters: zod
      .strictObject({
        dzen: zod.number(),
        telegram: zod.number(),
        instagram: zod.number(),
      })
      .describe('Количество материалов по платформам.'),
    pinnedMaterial: zod
      .strictObject({
        id: zod.string().describe('Идентификатор материала.'),
        placeId: zod.string().describe('Идентификатор места, к которому относится материал.'),
        platform: zod
          .enum(['dzen', 'telegram', 'instagram'])
          .describe('Платформа, на которой опубликован материал.'),
        type: zod.enum(['post', 'reel', 'video']).describe('Тип материала.'),
        title: zod
          .string()
          .nullable()
          .describe(
            'Заголовок материала. Для импортированных материалов может быть `null`, если источник не дает надежный ручной title.',
          ),
        publishedAt: zod.iso
          .date()
          .describe('Календарная дата публикации материала в формате `YYYY-MM-DD`.'),
        durationSec: zod.number().nullable().describe('Длительность в секундах для видеоформатов.'),
        redirectUrl: zod
          .string()
          .nullable()
          .describe(
            'Same-origin redirect URL для публичного открытия материала без прямого внешнего href. Поле заполняется только для публично безопасных target URL.',
          ),
      })
      .describe(
        'Публичный материал, связанный с местом. Исходный внешний URL не отдается; публичные клиенты должны использовать `redirectUrl`.',
      )
      .nullable()
      .describe(
        'Закреплённый материал места, если он назначен. Исходный внешний URL не отдается; клиенты должны использовать только `redirectUrl`, когда он доступен.',
      ),
  })
  .describe(
    'Детальная карточка места с публично-безопасным pinned material без исходного внешнего URL и счетчиками по платформам.',
  );

export const GetPlaceDetail404Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

/**
 * Возвращает бинарное содержимое публичного cover-фото активного места.
 * @summary Get place cover photo
 */
export const getPlaceCoverPhotoPathPlaceSlugRegExp = new RegExp('^[a-z0-9]+(?:-[a-z0-9]+)\*$');

export const GetPlaceCoverPhotoParams = zod.strictObject({
  placeSlug: zod
    .string()
    .regex(getPlaceCoverPhotoPathPlaceSlugRegExp)
    .describe('Публичный slug места.'),
});

export const GetPlaceCoverPhoto404Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

/**
 * Возвращает до 100 материалов, связанных с указанным активным местом, с опциональным фильтром по платформе.
 * @summary List place materials
 */
export const listPlaceMaterialsPathPlaceSlugRegExp = new RegExp('^[a-z0-9]+(?:-[a-z0-9]+)\*$');

export const ListPlaceMaterialsParams = zod.strictObject({
  placeSlug: zod
    .string()
    .regex(listPlaceMaterialsPathPlaceSlugRegExp)
    .describe('Публичный slug места.'),
});

export const ListPlaceMaterialsQueryParams = zod.strictObject({
  platform: zod
    .enum(['dzen', 'telegram', 'instagram'])
    .optional()
    .describe('Фильтр по платформе публикации материала.'),
});

export const ListPlaceMaterials200Response = zod
  .strictObject({
    items: zod
      .array(
        zod
          .strictObject({
            id: zod.string().describe('Идентификатор материала.'),
            placeId: zod.string().describe('Идентификатор места, к которому относится материал.'),
            platform: zod
              .enum(['dzen', 'telegram', 'instagram'])
              .describe('Платформа, на которой опубликован материал.'),
            type: zod.enum(['post', 'reel', 'video']).describe('Тип материала.'),
            title: zod
              .string()
              .nullable()
              .describe(
                'Заголовок материала. Для импортированных материалов может быть `null`, если источник не дает надежный ручной title.',
              ),
            publishedAt: zod.iso
              .date()
              .describe('Календарная дата публикации материала в формате `YYYY-MM-DD`.'),
            durationSec: zod
              .number()
              .nullable()
              .describe('Длительность в секундах для видеоформатов.'),
            redirectUrl: zod
              .string()
              .nullable()
              .describe(
                'Same-origin redirect URL для публичного открытия материала без прямого внешнего href. Поле заполняется только для публично безопасных target URL.',
              ),
          })
          .describe(
            'Публичный материал, связанный с местом. Исходный внешний URL не отдается; публичные клиенты должны использовать `redirectUrl`.',
          ),
      )
      .describe('Материалы места в стабильном порядке отображения.'),
  })
  .describe('Ограниченный список материалов места без исходного внешнего URL.');

export const ListPlaceMaterials400Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

export const ListPlaceMaterials404Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');

/**
 * Выполняет временный redirect на сохраненный URL публичного материала. Endpoint не принимает внешний URL от клиента и работает только для материалов активных мест с безопасной https-ссылкой платформы.
 * @summary Redirect to material URL
 */
export const RedirectMaterialParams = zod.strictObject({
  materialId: zod.string().describe('Идентификатор материала.'),
});

export const RedirectMaterial404Response = zod
  .strictObject({
    statusCode: zod.number().describe('HTTP status code ответа.'),
    message: zod
      .union([zod.string(), zod.array(zod.string())])
      .describe('Сообщение ошибки. Для DTO validation NestJS обычно возвращает массив строк.'),
    error: zod.string().optional().describe('Стандартное HTTP reason summary от NestJS.'),
  })
  .describe('Стандартный JSON body, который NestJS возвращает для `HttpException`.');
