/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * Amazing EKB backend contract.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * @summary Public place list.
 */
export const placesListQueryPageDefault = 1;
export const placesListQueryPageMax = 1000;

export const placesListQueryPageSizeDefault = 20;
export const placesListQueryPageSizeMax = 100;

export const placesListQuerySearchMax = 100;

export const placesListQueryCategoryIdMax = 100;

export const PlacesListQueryParams = zod.strictObject({
  page: zod.number().min(1).max(placesListQueryPageMax).default(placesListQueryPageDefault),
  pageSize: zod
    .number()
    .min(1)
    .max(placesListQueryPageSizeMax)
    .default(placesListQueryPageSizeDefault),
  search: zod.string().max(placesListQuerySearchMax).optional(),
  categoryId: zod.string().max(placesListQueryCategoryIdMax).optional(),
});

export const placesList200ResponseItemsItemCountersDzenMin = 0;

export const placesList200ResponseItemsItemCountersInstagramMin = 0;

export const placesList200ResponseItemsItemCountersTelegramMin = 0;

export const placesList200ResponseTotalMin = 0;

export const PlacesList200Response = zod.strictObject({
  items: zod.array(
    zod.strictObject({
      category: zod.strictObject({
        coverImageUrl: zod.string().nullable(),
        id: zod.string(),
        slug: zod.string(),
        title: zod.string(),
      }),
      counters: zod.strictObject({
        dzen: zod.number().min(placesList200ResponseItemsItemCountersDzenMin),
        instagram: zod.number().min(placesList200ResponseItemsItemCountersInstagramMin),
        telegram: zod.number().min(placesList200ResponseItemsItemCountersTelegramMin),
      }),
      coverImageUrl: zod.string().nullable(),
      id: zod.string(),
      slug: zod.string(),
      status: zod.enum(['active', 'hidden']),
      summary: zod.string(),
      tags: zod.array(zod.string()),
      title: zod.string(),
    }),
  ),
  page: zod.number().min(1),
  pageSize: zod.number().min(1),
  total: zod.number().min(placesList200ResponseTotalMin),
});

/**
 * @summary Public place detail.
 */
export const PlacesGetParams = zod.strictObject({
  placeSlug: zod.string(),
});

export const placesGet200ResponseCountersDzenMin = 0;

export const placesGet200ResponseCountersInstagramMin = 0;

export const placesGet200ResponseCountersTelegramMin = 0;

export const placesGet200ResponsePinnedMaterialOneDurationSecMin = 0;

export const PlacesGet200Response = zod.strictObject({
  category: zod.strictObject({
    coverImageUrl: zod.string().nullable(),
    id: zod.string(),
    slug: zod.string(),
    title: zod.string(),
  }),
  counters: zod.strictObject({
    dzen: zod.number().min(placesGet200ResponseCountersDzenMin),
    instagram: zod.number().min(placesGet200ResponseCountersInstagramMin),
    telegram: zod.number().min(placesGet200ResponseCountersTelegramMin),
  }),
  coverImageUrl: zod.string().nullable(),
  id: zod.string(),
  mapsUrl: zod.url().nullable(),
  pinnedMaterial: zod
    .strictObject({
      durationSec: zod.number().min(placesGet200ResponsePinnedMaterialOneDurationSecMin).nullable(),
      id: zod.string(),
      placeId: zod.string(),
      platform: zod.enum(['dzen', 'telegram', 'instagram']),
      publishedAt: zod.iso.date(),
      redirectUrl: zod.string().nullable(),
      title: zod.string().nullable(),
      type: zod.enum(['post', 'reel', 'video']),
    })
    .nullable(),
  slug: zod.string(),
  status: zod.enum(['active', 'hidden']),
  summary: zod.string(),
  tags: zod.array(zod.string()),
  title: zod.string(),
});

/**
 * @summary Public place materials.
 */
export const PlaceMaterialsListParams = zod.strictObject({
  placeSlug: zod.string(),
});

export const PlaceMaterialsListQueryParams = zod.strictObject({
  platform: zod.enum(['dzen', 'telegram', 'instagram']).optional(),
});

export const placeMaterialsList200ResponseItemsItemDurationSecMin = 0;

export const PlaceMaterialsList200Response = zod.strictObject({
  items: zod.array(
    zod.strictObject({
      durationSec: zod
        .number()
        .min(placeMaterialsList200ResponseItemsItemDurationSecMin)
        .nullable(),
      id: zod.string(),
      placeId: zod.string(),
      platform: zod.enum(['dzen', 'telegram', 'instagram']),
      publishedAt: zod.iso.date(),
      redirectUrl: zod.string().nullable(),
      title: zod.string().nullable(),
      type: zod.enum(['post', 'reel', 'video']),
    }),
  ),
});

/**
 * @summary Place cover image.
 */
export const PlacesGetPhotoParams = zod.strictObject({
  placeSlug: zod.string(),
});
