/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Amazing EKB Hub API
 * Amazing EKB backend contract.
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * @summary Administrative category list.
 */
export const AdminCategoriesList200Response = zod.strictObject({
  items: zod.array(
    zod.strictObject({
      coverImageUrl: zod.string().nullable(),
      createdAt: zod.iso.datetime({ offset: true }),
      id: zod.string(),
      slug: zod.string(),
      status: zod.enum(['draft', 'active']),
      title: zod.string(),
      updatedAt: zod.iso.datetime({ offset: true }),
    }),
  ),
});

/**
 * @summary Created category.
 */

export const adminCategoriesCreateBodySlugRegExp = new RegExp('^[a-z0-9]+(?:-[a-z0-9]+)\*$');

export const AdminCategoriesCreateBody = zod.strictObject({
  slug: zod.string().min(1).regex(adminCategoriesCreateBodySlugRegExp).nullish(),
  title: zod.string().min(1),
});

export const AdminCategoriesCreate201Response = zod.strictObject({
  coverImageUrl: zod.string().nullable(),
  createdAt: zod.iso.datetime({ offset: true }),
  id: zod.string(),
  slug: zod.string(),
  status: zod.enum(['draft', 'active']),
  title: zod.string(),
  updatedAt: zod.iso.datetime({ offset: true }),
});

/**
 * @summary Deleted category.
 */
export const AdminCategoriesDeleteParams = zod.strictObject({
  categoryId: zod.string(),
});

/**
 * @summary Administrative category.
 */
export const AdminCategoriesGetParams = zod.strictObject({
  categoryId: zod.string(),
});

export const AdminCategoriesGet200Response = zod.strictObject({
  coverImageUrl: zod.string().nullable(),
  createdAt: zod.iso.datetime({ offset: true }),
  id: zod.string(),
  slug: zod.string(),
  status: zod.enum(['draft', 'active']),
  title: zod.string(),
  updatedAt: zod.iso.datetime({ offset: true }),
});

/**
 * @summary Updated category.
 */
export const AdminCategoriesUpdateParams = zod.strictObject({
  categoryId: zod.string(),
});

export const adminCategoriesUpdateBodySlugRegExp = new RegExp('^[a-z0-9]+(?:-[a-z0-9]+)\*$');

export const AdminCategoriesUpdateBody = zod.strictObject({
  slug: zod.string().min(1).regex(adminCategoriesUpdateBodySlugRegExp).optional(),
  title: zod.string().min(1).optional(),
});

export const AdminCategoriesUpdate200Response = zod.strictObject({
  coverImageUrl: zod.string().nullable(),
  createdAt: zod.iso.datetime({ offset: true }),
  id: zod.string(),
  slug: zod.string(),
  status: zod.enum(['draft', 'active']),
  title: zod.string(),
  updatedAt: zod.iso.datetime({ offset: true }),
});

/**
 * @summary Category with replaced cover photo.
 */
export const AdminCategoriesUploadPhotoParams = zod.strictObject({
  categoryId: zod.string(),
});

export const AdminCategoriesUploadPhotoBody = zod.strictObject({
  photo: zod.instanceof(File),
});

export const AdminCategoriesUploadPhoto200Response = zod.strictObject({
  coverImageUrl: zod.string().nullable(),
  createdAt: zod.iso.datetime({ offset: true }),
  id: zod.string(),
  slug: zod.string(),
  status: zod.enum(['draft', 'active']),
  title: zod.string(),
  updatedAt: zod.iso.datetime({ offset: true }),
});
